electron/build-tools

common/generate-config.js, config.example.yml, nix/commands/sync.sh, win/commands/sync.bat
Allows using HTTPS instead of SSH when resetting Electron's & Node's origins.
=> feat: allow optional HTTPS for git origin

common/validate-env.js
This was failing on:
```sh
electron-gn-scripts on git:master ❯ e generate-config                          7:53PM
/Users/codebytere/electron-gn-scripts/common/validate-env.js:22
fail('You must create a config.yml file in the root of this repository, copy config.example.yml to get started');
^
ReferenceError: Cannot access 'fail' before initialization
at Object.<anonymous> (/Users/codebytere/electron-gn-scripts/common/validate-env.js:22:3)
.... rest of stacktrace
```
=> fix: anonymous functions don't get hoisted

README.md, nix/commands/debug.sh, nix/e
Adds a new cross-platform command for native debugging with lldb/gdb: `e debug`.
=> feat: add debug command

README.md, nix/commands/export-patches.sh, nix/e
Adds a new command `e export-patches [dir]` to export patches to the desired patch folder in Electron source tree.
=> feat: add command for patch exporting

nix/commands/__load-config.sh
`realpath` is a [linux-only](http://man7.org/linux/man-pages/man3/realpath.3.html) command and so errors on mac:
```sh
src on git:0fa60ec54270 ❯ e export-patches                                     8:46AM
/Users/codebytere/electron-gn-scripts/nix/commands/__load-config.sh: line 5: realpath: command not found
```
cc @ckerr
=> fix: realpath is linux-only

.gitignore, README.md, nix/commands/__constants.sh, nix/commands/__tools.sh, nix/commands/bootstrap.sh, nix/commands/build.sh, nix/commands/fetch.sh, nix/commands/pr.sh, nix/commands/sync.sh, nix/commands/test.sh, nix/commands/testnode.sh, nix/evm
When invoking depot tools commands used by our scripts (gn, gclient, ninja), ensure that the depot_tools repo is cloned into `electron-gn-scripts/third_party/depot_tools` and temporarily prepend that directory into the path. Also, give `depot_tools` a pull every fortnight to stay up-to-date.
Likewise, ensure that `yarn install` has been called before invoking node.
=> feat: on nix, automate depot-tools installation and 'yarn install'

nix/commands/fetch.sh
Does what it says on the tin. `e fetch` now allows an optional extra argument that is either an absolute or relative path. If none is specified, `$PWD/electron` is still the default.
=> feat: let users specify the fetch target directory

nix/commands/export-patches.sh
Fixes a double-quote issue that caused bad variable substitution:
cc @ckerr
=> fix: array key variable substitution in export-patches

src/evm-config.js
The yml support is fine and I _love_ the `extends` feature
There are a couple of issues in qol as-is
1. (bug) it unconditionally serializes as json, even though the file returned by pathOf() can be `.yml`. So any new config that you create with `e init` will have a `.yml` suffix but be formatted as json.
2. (wart) The error thrown in `setCurrent()` will only say that it tested the `evm.name.yml` file, implying that other formats were ignored. Ideally that error would show all the files that were tried
3. (wart) Since yaml is a superset of json, the if-else in loadConfigFileRaw() isn't necessary -- everything can be passed through yaml.load
4. It reads but doesn't write yaml, so this half-supported feature is only really good for people hand-crafting their own config files -- iow, for you …
=> fix: choose serialize format based on file suffix

package.json, src/e-test.js, src/evm-config.js, yarn.lock
This adds support for yaml and a new `extends` attribute in config objects to allow config re-use.
It also fixes a bug in `e test` where `ELECTRON_OUT_DIR` was not set correctly
=> chore: add support for yaml and extends

src/util.js
Allow using a custom `depot_tools` path in the event one already existed.
=> feat: allow custom depot_tools path

.github/workflows/lint.yml, src/e
Closes https://github.com/electron/build-tools/issues/28.
`.allowUnknownOptions()` allows unknown options to be passed to a command without throwing an error, but with one twist - it only considers options to be those that start with `--`. That means that if we were to run `e start my-electron-app` it would consider `my-electron-app` to be an `arg`, and so with current code would just never be passed to `execFileSync`, since we were assuming all non-specified strings after the command would get pushed into `unknown`.
Also added some help text to both `e node` and `e start`.
cc @MarshallOfSound and @ckerr
=> fix: properly pass extra cli options

package.json, src/evm-config.js, yarn.lock
We already have to install js-yaml for the nyc-based coverage tests, so this change reduces our dependency list. It's also better maintained and generates prettier output.
=> chore: use js-yaml instead of yaml-js

src/e-patches.js
Fixes `e patches <dir>` in the wake of https://github.com/electron/build-tools/pull/24.
`evmConfig.current()` now returns:
```
{
gen: {
args: [
'import("//electron/build/args/testing.gn")',
'cc_wrapper="/Users/codebytere/Developer/electron-gn/src/electron/external_binaries/sccache"'
],
out: 'Testing'
},
root: '/Users/codebytere/Developer/electron-gn',
origin: {
electron: 'https://github.com/electron/electron',
node: 'https://github.com/nodejs/node'
},
env: {
GIT_CACHE_PATH: '/Users/codebytere/.git_cache',
SCCACHE_BUCKET: 'electronjs-sccache-ci',
SCCACHE_CACHE_SIZE: '40G',
SCCACHE_TWO_TIER: true
}
}
```
which meant that `evmConfig.current().config` was `undefined` and errored.
=> fix: evm config destructure in patches

src/e-debug.js, src/e-patches.js
Get them by reading and parsing electron/patches/config.json.
=> refactor: get patch targets from patches directory

README.md, package.json, src/e
Previously, unknown commands would fail silently; no help text would be output and nothing would happen - this might be confusing to users.
This PR checks commands against a list of valid commands and outputs a help text if an unknown command is run.
Before:
After:
cc @MarshallOfSound @ckerr
=> feat: fail gracefully on unknown commands

.github/workflows/lint.yml, .github/workflows/pull_request.yml, README.md, yarn.lock
Previously, we committed our `yarn.lock` but used `npm` both in CI and in documentation, which created some issues because npm and yarn don't always resolve identical versions.
This ensure we use yarn everywhere.
cc @ckerr
=> chore: use yarn everywhere

src/e-show.js
Does what it says on the tin: `$ e show outdir` will print out `/$root/src/out/$out`.
=> feat: add 'e show outdir'

src/e
This commit broke some command parsing, e.g. "e show current" and "e show --help" did not work with this fix.
NB: even though this was @codebytere's commit, the bug introduced here is probably [mine](https://github.com/electron/build-tools/pull/34#issuecomment-555123136)... :roll_eyes: 
Also, this is a manual revert rather than a straight `git revert` because that commit also included some changes that we need to keep wrt bumping prettify.
CC @codebytere
=> fix: revert 98b4ba7 due to unexpected side effects

README.md, src/e, src/e-load-macos-sdks.js, src/util.js
Not sure if we should run this automatically or not, it makes a few assumptions and advanced users may not meet those assumptions.
This will auto-link older macOS SDKs so that we don't have to mess around with Xcode versions on new set ups.
=> feat: add a load-macos-sdks command to help initial setup

README.md
The instructions for adding the `build-tools/src` directory to a user's path works on Windows if using cmd, but not if using PowerShell. This PR updates the README to show how to do it on both.
=> docs: show how to add `e` to a win powershell path

src/e-pr.js
Fixes `e pr` for branches following the new `8-x-y` pattern.
Previously, this command would try to open against `8-0-x` for a pr against `8-x-y`, which is incorrect.
=> fix: correctly guess target branch for >= 8

src/e-build.js, src/e-init.js, src/util.js, tests/e-init-spec.js
This PR adds configuration options for use with the Goma distibuted build system. This approach assumes that we'll be performing the authentication step for Goma at init-time, and then if we've stated we are using goma but are not authed properly an error is thrown at build-time. 
cc @MarshallOfSound @jkleinsc
=> feat: add configuration options for Goma

src/e-init.js
`GIT_CACHE_PATH` is treated as an sccache-only variable, causing it to be omitted if Goma is in use. I _think_ this is in error, since `GIT_CACHE_PATH` is used by gclient sync rather than by the build?
@codebytere is this correct?
=> fix: keep GIT_CACHE_PATH regardless of Goma

README.md
Make it clearer that `--root=/path/to/new/electron/directory ` is an optional override path.
=> docs: clarify new directory needed

src/e-build.js
This makes it so if you don't provide a `-j` value and goma is enabled we provide one for you that matches our cluster recommendations.
=> chore: set j values when in goma build

README.md, package.json, src/download.js, src/e, src/e-load-xcode.js, src/hash.js, src/util.js, yarn.lock
This is so that Goma cache hit rates will be higher when using build tools.  The xcode version being used is a DEFINE in the electron build so we need to all be on the same version to get the best cache rates.  Currently this is using 10.3
=> feat: add support for downloading a fixed and known version of xcode

src/e-init.js
Previously was `undefined`, which caused `e init` to die when dumping config to yaml:
```sh
$ e init --root=/tmp/foo foo
Creating /tmp/foo
Running "python /home/charles/electron/build-tools/third_party/depot_tools/gclient.py config --name src/electron --unmanaged https://github.com/electron/electron" in /tmp/foo
ERROR YAMLException: unacceptable kind of an object to dump [object Undefined]
at writeNode (/home/charles/electron/build-tools/node_modules/js-yaml/lib/js-yaml/dumper.js:756:13)
at writeBlockMapping (/home/charles/electron/build-tools/node_modules/js-yaml/lib/js-yaml/dumper.js:634:10)
at writeNode (/home/charles/electron/build-tools/node_modules/js-yaml/lib/js-yaml/dumper.js:727:9)
at dump (/home/charles/electron/build-tools/node_modules/js-yaml/lib/js-yaml/dumper.js:817:7)
at …
```
=> fix: set the `--use-goma` default value to false

package.json, src/utils/xcode.js, yarn.lock
Quite a few people have been seeing `ENOBUFS` while unzipping Xcode, this fixes that by completely ignoring `stdout` for the unzip command.
=> fix: ignore stdio for the unzip command to prevent ENOBUFS

src/e, src/utils/depot-tools.js, src/utils/goma.js, src/utils/macos-sdks.js, src/utils/paths.js, src/utils/sccache.js, src/utils/xcode.js
Sometimes you want to be able to run `depot_tools` like `gn` manually, this lets you do it.
It's as easy as
```bash
e gn gen
e goma_ctl status
```
=> feat: add unknown command handler to run depot_tools cmds

src/e-init.js
Fix a race condition whereby the external binaries won't have finished downloading by the time we run build, so goma auth would not work properly.
=> fix: race condition with external binary download

src/e
Closes https://github.com/electron/build-tools/issues/56.
We were setting `stdio: ['ignore', 'inherit', 'inherit']` and should just have been passing `stdio: 'inherit'`
=> fix: e start --inherit not working

src/e-build.js
Noticed while testing the goma stuff, we need to automatically re-run `gn gen` if the args config does not match the args file
=> fix: auto re-run gn gen if the args do not match

src/e-show.js
Pretty straightforward: adds a simple convenience to open Goma's status page from the command line.
=> feat: add 'e show goma' to open localhost:8088

tools/zsh/_e
When typing a partial filename after `e run`, use zsh's file completion to try and match it. For example `e run m<tab>'` might try to match `e run main.js`
Works for both 'start'/'run' and for 'node'
=> feat: add file tab completion to 'e start' on zsh

src/evm-config.js
This is helpful for building other projects with build tools like `Chromium`.  I can get the full build flow working with this config now.
```yaml
goma: cluster
root: /Users/sattard/projects/chromium
binaryName: chromium
gen:
args:
- is_debug = false
- import("/Users/{user}/projects/electron/build-tools/third_party/goma.gn")
out: Testing
env:
CHROMIUM_BUILDTOOLS_PATH: /Users/sattard/projects/chromium/src/buildtools
GIT_CACHE_PATH: /Users/sattard/.git_cache
```
=> feat: add support for custom binaryName

src/evm-config.js
As i had an older config, i hadn't added `CHROMIUM_BUILDTOOLS_PATH` to `env` - this cause some unexpected errors:
```sh
Running "/Users/codebytere/build-tools/third_party/depot_tools/gn.py gen "out/Testi
ng" --args="import(\"//electron/build/args/testing.gn\") import(\"/Users/codebytere
/build-tools/third_party/goma.gn\")"" in /Users/codebytere/Developer/electron-gn/sr
c
gn.py: Could not find checkout in any parent of the current path.
This must be run inside a checkout.
ERROR Error: Command failed: /Users/codebytere/build-tools/third_party/depot_tools/
gn.py gen "out/Testing" --args="import(\"//electron/build/args/testing.gn\") import
(\"/Users/codebytere/build-tools/third_party/goma.gn\")"
at checkExecSyncError (child_process.js:621:11)
at Object.execSync (child_process.js:657:15)
at …
```
=> fix: default missing CHROMIUM_BUILDTOOLS_PATH

README.md
Add a little more information about some of the command-specific documention and clean up examples. 
=> docs: improve documentation verbosity

README.md, src/evm-config.js
The intent is to follow the same workflow as nvm: e has a default active config (just as nvm has a default active version of Node.js), but that can be overridden by the user on a per-shell basis.
What's the same as EVM_SESSION_ID: since `e` is a JS script and can't modify its caller's environment variables, the goal is accomplished by having more than one 'current' file. The default file is $EVM_CONFIG/evm-current.txt. An optional environment variable specifies where to find an optional file to override the default.
What's different from EVM_SESSION_ID: EVM_CURRENT_FILE specifies the filename itself, so evm-config.js doesn't need new folder code and $EVM_CONFIG/sessions/ doesn't accumulate dead session folders. Instead, the file can be in $TMPDIR so that the OS will clean it up later. …
=> refactor: use EVM_CURRENT_FILE to avoid fs clutter

README.md, src/evm-config.js
Fixes #72 
By adding `export EVM_SESSION_ID=$(uuid)` to your `.bashrc` or `.zshrc` file you can get per-session evm configs, so you can use different configs in different shells.
`e use X` will set both your session and the global config to `X`
`e <anything>` will attempt to read your session, if it fails it will read global and then instantly set that result to your session
=> feat: add support for EVM_SESSION_ID to have per-shell config selection

src/e-build.js, src/utils/goma.js
goma util functions were structured such that `downloadAndPrepareGoma` was only run if you were authenticating or checking for auth status, which meant that cache-only goma users would not see goma properly downloaded to `third_party`.
The following failure would occur (as seen by cache-only user):
```sh
Running "goma_ctl.py ensure_start" in C:\Users\hepadala\build-tools\third_party\goma
ERROR Error: spawnSync python ENOENT
at Object.spawnSync (internal/child_process.js:1041:20)
at spawnSync (child_process.js:607:24)
at Object.execFileSync (child_process.js:634:15)
at Object.ensureGomaStart [as ensure] (C:\Users\hepadala\build-tools\src\utils\goma.js:113:16)
at runNinja (C:\Users\hepadala\build-tools\src\e-build.js:46:10)
at Object.<anonymous> …
```
=> fix: buildtools now downloading for cache-only

src/e-build.js
We were directly invoking `gn.py`, which skips over the two platform-specific invokers, `gn` and `gn.bat`. Those two files run important path setup steps, and so we should be mimicking the approach taken by Chromium as seen [here](https://source.chromium.org/chromium/chromium/src/+/master:build/check_gn_headers.py;l=98?q=%22gn.bat%22&ss=chromium&originalUrl=https:%2F%2Fcs.chromium.org%2F).
=> fix: use gn.bat on win32

src/utils/goma.js
Latest chromium roll requires some new clang things that required a new goma client
=> fix: use new goma client for latest chromium roll

package.json, src/e-test.js, yarn.lock
This does three things
* Auto-copies the `.lib` file so that native modules are linked correctly
* Passes your env config into the test runner
* Forces the test runner to use a known good version of `node-gyp` instead of the _mauybe bad_ global version
=> chore: improve the experience of running tests on windows

tests/e-show-spec.js, tests/sandbox.js
I'm running Windows 10 64-bit and after running `yarn test`, I received failures.
First issue was caused by `nyc` not spawning. Had to switch to use `npm.cmd` to fix it.
Second issue was a test not checking for Windows-only environment vars getting set.
https://github.com/electron/build-tools/blob/f9aa0d26bc37dfb52cdd7b692b2963a0148d09b6/src/e-init.js#L39-L44
=> fix: windows tests failing

src/e-init.js
With the old code we were syncing then checking git settings, at that point it was too late if the settings were wrong, we had a polluted cache.  We should fail-fast here if the settings are wrong
=> fix: check git settings before we do anything

src/e-init.js, src/e-sync.js, src/utils/depot-tools.js
Fixes #93 
This works at least for master, haven't tested older branches but we might need to make toolchains for older branches separately.  If chromium changes the hash we'll need to make a new toolchain and put it in the env here.
=> feat: use an electron provided windows toolchain

package.json, src/e, src/e-init.js, src/e-sync.js, src/utils/deps-check.js, src/utils/get-path.bat, src/utils/git.js, src/utils/maybe-auto-fix.js, src/utils/refresh-path.js, src/utils/which.js, yarn.lock
With these changes I can install Node, Git and `build-tools` and run 
`e init --root=~/electron --bootstrap testing` and it Just Works out of the box, it will prompt to install missing dependencies, fix incorrect git configuration, etc.
Closes #102 
Closes #104 
Currently stacked on top of #96 for Better Windows Reasons
=> feat: make build-tools error-correcting on Windows

.gitignore, src/e, src/e-check-for-updates.js
Every four hours the next `build-tools` command you run will try to `git pull` and `npx yarn` if your HEAD changed.
This is rudimentary but should keep users up to date with important things like `goma` and `xcode`.
=> feat: auto-update the build-tools every 4 hours

src/e-load-xcode.js, src/utils/hash.js, src/utils/xcode.js
Electron 8, 9 and master are all on Xcode 11.  Let's get cache hits from CI again
I'm going to work after this PR on detecting which Xcode version to use based on the `circle.yml` file which should mean we won't have to manually switch versions like this too often.
This has a little bit of work towards handling multiple Xcode versions and hot-swapping them
=> feat: switch to Xcode 11.1

src/e-build.js, src/utils/goma.js
If auth failed previously it'd explode on your terminal like:
```sh
electron on git:master ❯ e d goma_auth info                                      10:06AM
Running "python goma_auth.py info" in /Users/codebytere/build-tools/third_party/goma
E0305 10:08:04.187968 336999872 goma_fetch.cc:249] fetch POST https://login.microsoftonline.com/electronad.onmicrosoft.com/oauth2/token err=-1  Got HTTP error:400 dest=login.microsoftonline.com:443 url_path_prefix=/electronad.onmicrosoft.com/oauth2/token use_ssl socket_read_timeout=10s retry_backoff=500ms .. 5s
Traceback (most recent call last):
File "goma_auth.py", line 669, in <module>
sys.exit(main())
File "goma_auth.py", line 665, in main
return action()
File "goma_auth.py", line 584, in Info
err = VerifyRefreshToken(config)
File "goma_auth.py", …
```
=> fix: gracefully catch auth error

src/utils/goma.js
goma.auth needs to inherit stdin to accept data policy.
=> fix: stdio should be inherit in goma.auth

src/e-build.js
Previously running `e build` without an authenticated goma would result in you being prompted to auth and then having to run `e build` again.  This fixes that
=> fix: only exit if the exit code is not 0

src/e-sync.js
This helps for debugging and it's not like any of us are using network drives / two syncs at a time
=> chore: make the default sync command ignore locks and be verbose

package.json
Prevent accidental publish of this repo to npm, as in order to preserve auto-update functionality we plan to use https://github.com/electron/build-tools-installer.
=> chore: prevent accidental publish

src/e-check-for-updates.js
Fixes an issue where a pull might fail if being run on a non-`master` branch. Throws an error if an update is run from a non-master branch of `build-tools`.
=> fix: only run updates from master

src/e, src/e-check-for-updates.js
Follow-up to 3c5d043a2956f41c704023609cef2971f789ce04 and 7cd0f88d6f4e65826547015690036547a1e612c0 to ensure that `git` is called from the correct directory.
=> fix: set correct cwd in check-for-updates

src/e
Bug description: scripts that rely on build-tools will fail occasionally if build-tools hasn't had a recent update check. For example some of my shell scripts have calls along the lines of `FOO="$(e show exec)"` and fail when FOO has "Checking for build-tools updates" instead of a path.
When the update script is run passively, its stdout is redirected to stderr: it's still useful there as a user-visible message, but doesn't interfere with expected values in stdout.
=> fix: don't pollute stdout with passive update logs

src/e, src/e-show.js, src/utils/goma.js
Follows up https://github.com/electron/electron/pull/22784 discussion: we want CI to be able to use build-tools' goma utils in a way that won't break if `utils/goma.js` ever gets refactored. So this PR adds three new commands for CI to use:
* `e show gomadir` *(prints goma.dir)*
* `e show gomagn` *(prints goma.gnFilePath)*
* `e update-goma` *(runs goma.downloadAndPrepare())*
In addition, `goma.downloadAndPrepare()` now returns a checksum string on success so that `e update-goma` has something to log on success. This isn't essential -- the exit code already shows success/failure -- but is visually nice.
CC @jkleinsc @MarshallOfSound
=> feat: add goma hooks that can be invoked by CI

README.md
Now that we have a bespoke installer for `build-tools`, we no longer need to concern ourselves with manual PATH management.
cc @ckerr @itsananderson @MarshallOfSound
=> docs: remove outdated README section

README.md
As in title, this command is not required
=> docs: load-xcode is run automatically nowadays

README.md, src/e, src/e-open.js
This is a feature I've been using for awhile as a bash script and thought it might be useful to other people working on the codebase.
Basically it's a quick helper to open the PR page from a commit's abbreviated sha1.
For example, `e open 0920d01` will find the commit with an abbreviated sha1 of `0920d01`, see that it's associated with pull request #23450, and open https://github.com/electron/electron/pull/23450 in your browser. Since you can pass in a pull request or issue number as well, `e open 23450` would do the same thing.
=> feat: add "e open <pull | sha>"

src/e-sync.js
Silences a warning that began @ [14a83ae](https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/14a83aec5603e47208a4a41c8c085a1991d33d47):
> Warning: ignore_locks is no longer used. Please remove its usage.
=> chore: do not pass --ignore_locks to gclient sync.

src/utils/xcode.js
Xcode-11.5.zip did not have the expected Xcode.app directory in it.  A new zip was uploaded with the correct structure.
=> chore: fix Xcode 11.5 download

src/e-init.js, src/evm-config.js
Fixes #150 
If we run `init` with a config name that already exists, just let it fall through to sync if the config that already exists also points at the currently targeted "root" directory.
=> fix: re-initializing the same directory should just sync

src/e-patches.js
Real straightfoward, what this patch does is add an `e patches all` command which invokes `src/electron/script/export_all_patches.py` from the right directory and with the right config file.
=> feat: add "e patches all" option

src/e-build.js, src/e-show.js, src/utils/depot-tools.js, src/utils/goma.js
I hope this fixes an issue where the function would randomly return a not-authed error instead of a 200 cache-miss response.  Until we figure out why the not-authed responses arrive this should fix the issue by making goma not self-kill on a 401.
=> fix: do not kill the build on cache-only mode if the server dies

src/e-build.js, src/utils/goma.js
This makes some significantly faster happy paths in the `goma` checks we do before spawning `ninja`.  At least on my machine this makes the `ninja` command actually start several seconds sooner (tiny in the big picture but it was annoying watching it sit there every time)
=> perf: make e build actually spawn the build slightly faster by optimizing goma checks

src/e-build.js, src/utils/arm.js, src/utils/depot-tools.js, src/utils/refresh-path.js
Previously execSync was used, taking the full command line as a single string. This works great for commands like `git pull` but not great when we specify a command's pathname that can have a space in it. For example `C:\Users\My Name\e\third_party\depot_tools\gn` would see `C:\Users\My` as the command.
NB: the new code in e-build.js is cleaner, but it wasn't clear (to me, anyway) that the changed handling of escapes would work. FWIW I tested this change on both Win and POSIX.
Xref #133 and #134
CC @codebytere @MarshallOfSound
=> fix: use execFileSync when using a cmd with a path

README.md, src/e-test.js
Tweaks some wording and makes programmatic `--help` usage more front-and-center.
=> docs: add help commands to docs

src/e-test.js, src/utils/headers.js, src/utils/logging.js
As in title `e test --nan` now runs the nan test runner.  I'm thinking it would be better long term to have `e test --runners=main,node,nan` instead of three separate runners but that's more complicated work as it needs to be backwards compatible 😆
=> feat: add --nan support to 'e test'

README.md, src/e, src/evm-config.js, tests/e-remove-spec.js, tests/sandbox.js
This PR adds a new command for removing old build configurations.
- `e remove|rm <name>`
- Prevents the removal of the current used build config.
resolves #182
=> feat: add remove config command

README.md, src/e, src/e-load-xcode.js, src/evm-config.js, src/utils/logging.js
Closes https://github.com/electron/build-tools/issues/181.
Adds a new command to automatically overwrite an existing config to address any existing warnings about config updates.
=> feat: add e sanitize-config

src/utils/headers.js
Fixes #185. Thanks to @holmberd for reporting this and tracking down the source of the bug.
=> fix: point at the 'e' script's correct directory

src/e-sync.js
This should fix a small bug introduced [recently](https://github.com/electron/build-tools/commit/e198c2fef364ee3079c0919e235e18e15877ccf4#diff-6f5fbb459299d77d723c2fdfc7cdea4eR17) which was causing the `git remote` command to fail because it was not being run in the correct directory.
=> fix: run git command in correct working directory

src/e-init.js
Same as #143, just was a missed usage.
=> chore: drop usage of --ignore_locks with bootstrap

package.json
Subdirectories weren't included in the glob pattern, so `src/util/*.js` wasn't being covered by linting and prettier.
=> build: ensure full source coverage for linting

src/utils/goma.js
Fixes #91.
Now, don't ask me *why* it fixes it. 😄 Something to do with it hanging when stdio is actually attached. Didn't feel like spending more time debugging the root root cause once it was working.
@MarshallOfSound, I also have a branch that uses `start-goma.ps1` like you suggested, but that solution causes an extra window to appear briefly due to powershell, and that didn't seem ideal. Internally that script is also just using `goma_ctl.py ensure_start` so the extra layer of indirection didn't feel necessary one I resolved the hang.
=> fix: resolve hang when starting goma

.prettierignore
Ignore `third_party` files when running `prettier:write`. Accidentally formatted all the minified files in `third_party/depot_tools/third_party/coverage/htmlfiles/` just now 😅 
=> chore: ignore third_party js when formatting

src/e-show.js
Does what it says on the tin:
```sh
$ e show depotdir
/home/charles/electron/build-tools/third_party/depot_tool
```
This sibling to `e show gomadir` is a small change, but is nice-to-have for cases where I have a one-off task for depot-tools and want to manually add it to my path.
=> feat: add `e show depotdir`

.github/workflows/lint.yml, .github/workflows/pull_request.yml
`yarn install` was taking nearly a full minute on the Windows CI builds. Cache `node_modules` based on the hash of `yarn.lock` and save all the times. Tested on my own fork including updating `yarn.lock` to observe the cache busting.
=> chore: use caching on GitHub workflows

src/e-check-for-updates.js
Newer versions of git display the following:
```
Running "git pull" in /Users/codebytere/build-tools
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:
git config pull.rebase false  # merge (the default strategy)
git config pull.rebase true   # rebase
git config pull.ff only       # fast-forward only
You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.
```
this squelches the message by setting the strategy to rebase with autostash for minimal disruption.
=> chore: set divergent branch reconciliation strategy

src/utils/depot-tools.js
I don't believe there's any reason to have those on other platforms?
=> chore: only inject Windows env vars on Windows

src/e-show.js
Fix a regression that snuck in yesterday by trying to reassign the const variable `depot` in e-show.js
=> fix: reassign const in e-show

.github/workflows/test.yml
Only lint is running on push to `master` at the moment, running test as well might help catch a mix-up like #221 more quickly.
=> chore: run CI tests on push

src/e-pr.js
Refs https://github.com/electron/build-tools/commit/f61f22c57413d40cbf2eb2377c0cdbe3571ab33f.
it's possible that a user has no upstream configured for a given branch when backporting, and so we should continue to use `git rev-parse --abbrev-ref HEAD` to find the branch name. By unilaterally asking for a configured upstream, we see the following error:
```console
electron on git:no-artifacts-fail-release-11 ❯ e pr 11           10:48AM
fatal: no upstream configured for branch 'no-artifacts-fail-release-11'
/Users/codebytere/build-tools/src/e-pr.js:51
if (source.startsWith('fork/')) {
^
TypeError: Cannot read property 'startsWith' of undefined
at pullRequestSource (/Users/codebytere/build-tools/src/e-pr.js:51:14)
at Object.<anonymous> (/Users/codebytere/build-tools/src/e-pr.js:84:71)
at …
```
=> fix: e-pr when no upstream

src/e-pr.js
This is built on top of #222. ~~I'll rebase once (if) that gets merged, so leaving as draft for now.~~
Borrows [some code from electron/clerk](https://github.com/electron/clerk/blob/20f4ef1cb723ba84a1a6f3c2e90dd9b51f1d2ee3/src/note-utils.ts#L7-L26). I didn't see an easy way to share that code so opted for copy-and-paste.
~~Not sure what the feasible upper-limit is for injecting the release notes in the URL. I tested with PR 25064 and it could handle that 12 word sentence. I think for practical purposes it's probably fine.~~
EDIT: Remembered that Vuetify uses the same functionality for their issues (you create it on a separate site and it redirects to the GitHub issue with it filled out). Just tested it with two paragraphs of 'lorem ipsum' and that worked fine, so the notes length isn't a …
=> feat: add backport functionality to `e pr`

src/e-patches.js
Windows won't run filenames with no extensions as a program. Usually you can add `.cmd` to make that work, like how `@electron/build-tools` sets up `build-tools`, but since it's just Python, use Python to run it. Didn't seem worthwhile to add the `.cmd` alias in the main repo... although that might help people trying to run it without `build-tools`. I'll defer to others on which repo this fix should go on.
=> fix: make invocation of git-export-patches Windows-friendly

README.md
The documentation on this repo is great! I think most users looking to patch Electron will want to build against the specific version that they are using, so I figured it would be nice to have a specific section detailing how to do that.
=> docs: add building a specific Electron version

src/e
=> fix: do not allow help info for 'e d'

src/e-debug.js
Automatically run [chromium's `lldbinit.py` script](https://chromium.googlesource.com/chromium/src/+/master/docs/lldbinit.md) (also [bonus reading](https://www.electronjs.org/docs/development/debugging-instructions-macos)) when starting lldb with `e debug`, exactly like what is currently done for gdb.
This is a small QoL change to streamline using lldb. Currently it is expected you either create a `.lldbinit` file ✨ somewhere ✨ that you call `lldb` / `e debug` from (lldb looks in the cwd) containing `command script import /path/to/src/tools/lldb/lldbinit.py` or run it yourself in lldb or something else like that. This provides that little one-liner as an argument to `lldb` in the same way the `gdb` branch of the `e debug` command works.
=> feat: use lldb init script in `e debug`

src/utils/goma.js
Mitigates #229 by setting the number of Goma subprocesses on Mac OS equal to the number of CPUs. Has no effect on other build platforms.
The default on Mac is to use 3/4 subprocesses which is very slow. With this change, using `e build -j 16` on a recent 16" MacBook resulted in ~3x compile time improvement. Current Goma args can be checked at `http://localhost:8088/flagz` with Goma started.
=> perf: set number of Goma subprocs equal to CPUs on Mac

src/e, src/e-build.js, src/e-show.js, src/utils/goma.js
This PR makes it so that the goma batch files are run instead of the goma python scripts on Windows.
The goma batch files contain logic to select the right Python to use (i.e. vpython, falling back to python if that's not available), and then running the goma python script with that Python. By using the right Python, Windows users can avoid a misleading error about pywin32 not being installed.
=> feat: Use goma batch files in Windows

src/e, src/e-build.js, src/e-show.js, src/utils/goma.js
Fixes #258, fixes #252 
This PR changes the goma commands for Windows only. Now vpython (from depot_tools) runs the goma python files.
In PR #255, I changed it so that Windows ran batch files instead of python files, allowing `e build` to run smoothly on cmd. However, that change broke the building experience on git bash, and this solution makes it so that `e build` + goma login works on both git bash and cmd.
=> fix: switch Windows to use vpython instead of batch files

src/e, src/e-build.js, src/e-show.js, src/utils/goma.js
Though we should be using `vpython` on Windows (https://github.com/electron/build-tools/issues/252), it turns out that Windows has a hard time finding it unless we add `shell: true` to the spawn/exec opts.
Fixes https://github.com/electron/build-tools/issues/261
=> fix: add shell true to goma python/vpython calls

src/e
Open to suggestions on the command name but I think "npm" best describes what is going on here.  `e override` or `e local-run` where alternatives I considered.
This is super helpful when trying to run locally built Electron against app codebases.  `e npm yarn start` will simply trick the `electron` module into using your version of Electron :magic:
=> feat: add 'e npm' command to override electron path for local dev

src/utils/depot-tools.js
The last chromium roll required a toolchain update but we hadn't built one yet so we used the old one which was causing build errors like:
`../../buildtools/third_party/libc++/trunk/include\__config(297,14): fatal error: 'winapifamily.h' file not found`
(as seen here: https://github.com/electron/build-tools/issues/264#issuecomment-794365022).
This PR updates buildtools to use a new toolchain.  Fixes #264
=> chore: add new windows toolchain

package.json, src/e, src/e-cherry-pick.js, yarn.lock
This is an ad-hoc script that the security WG has been using for a while to backport security patches to older releases without having to do it by hand.  This generalizes the script a bit and makes it available for everyone easily through build-tools.
Example usage:
```bash
e cherry-pick https://chromium-review.googlesource.com/c/chromium/src/+/2823023 13-x-y
```
=> feat: add 'e cherry-pick' to auto-cherry-pick CLs into patches folder

src/e-pr.js
Improve UX slightly by throwing an error and stopping if the user accidentally passes an invalid backport number when running `e pr` with a backport.
=> fix: error if backport number invalid

src/e-init.js, tests/e-init-spec.js, tests/e-remove-spec.js
Closes https://github.com/electron/build-tools/issues/87.
Cleans up logic a bit to handle the case where `root` has been set to an existing directory but it's not been initialized with a `.gclient` file.
cc @MarshallOfSound @ckerr
=> fix: handle root dir existing with no .gclient

src/e-cherry-pick.js
Format of `BUG=chromium:123` wasn't being parsed
=> fix: add new pattern to get crbug number for v8 backports

src/utils/goma.js
fixes #91
By inheriting stdio when running `goma_ctl.py ensure_start`, it eventually exits which it isn't doing currently. The side effect is that the user will see the output below when first starting a build.
```
$ e build -j 18
Running "goma_ctl.py ensure_start" in C:\Users\Sam\.electron_build_tools\third_party\goma
Login as Sam Maddock
Using Server: athos.notgoma.com:443
using C:\Users\Sam\AppData\Local\Temp\goma as tmpdir
GOMA version 3f080e0675d1a389a0fc6ac19a2354f4d7a70d01@1606175303
waiting for compiler_proxy to respond...
waiting for compiler_proxy to respond...
waiting for compiler_proxy to respond...
waiting for compiler_proxy to respond...
waiting for compiler_proxy to respond...
compiler proxy (pid=16468) status: http://127.0.0.1:8088 ok
Now goma is ready!
Running "ninja.exe …
```
=> fix: goma ensure_start not exiting on Windows

src/e-pr.js
Otherwise if they can't be guessed you'll end up with a URL with `undefined` in it.
=> chore: show error if no source or target for pull request

src/e-pr.js
That line was throwing a `ReferenceError` since `pattern` should be `versionPattern`.
=> fix: use correct variable name in `guessPRTarget` warning

src/e-init.js
Fixes an issue resultant of https://github.com/electron/build-tools/pull/280 where it's no longer possible to initialize a new build config for a source root that has already been synced.
Use the `--force` flag to allow this.
=> fix: allow overwrite existing build config

src/e-build.js
Only ensure that XCode target is appropriate when building Electron targets.
=> fix: only ensure XCode for Electron

src/utils/xcode.js
https://github.com/electron/electron/pull/31741 moved a lot of information in the Circle CI config `config.yml` to a new `build_config.yml` file. The Xcode detection code relied on finding Xcode info in that old file path. This PR introduces the new file path as the source of truth, but still checks the old path if the first one fails to preserve backwards compatibility with electron repos older than that PR. Not sure when the old path should be removed from build tools though.
=> fix: detect xcode version after ci config change

src/e-build.js
It should be `Xcode`.
FYI: https://developer.apple.com/xcode/
=> chore: fix typo

src/e-build.js, src/e-sync.js, src/evm-config.js, src/utils/depot-tools.js
Fixes an issue where running `e sync` with an unaltered Chromium src checkout would fail to sync becuase it would try to set remotes for directories which didn't exist (`src/third_party/electron_node` and `src/electron`)
=> feat: enable using build-tools with Chromium

src/utils/depot-tools.js
Was noticing that if `depot_tools` is already at the start of your `PATH`, `e show env` still adds it to the front. Not functionally a problem, but does make it so `e show env` will never return clean since it will always modify `PATH` even if it doesn't need to.
=> chore: don't add depot_tools to PATH if already there

README.md
In the hello world example of build tools, the root directory is mentioned to be defaulting to `~/project/electron`. Whereas the config file generated defaults to `$PWD/electron` .
=> docs: fix root directory default in example

src/e, src/e-build.js, src/e-patches.js
Allow for listing all patch targets without re-exporting patches.
=> feat: expose e patches --list-targets

src/e-init.js, src/e-sync.js
Fixes #330.
I believe that issue was caused by [this CL landing](https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/3445785) which moved `gclient` to Python 3, and the way `build-tools` was invoking `gclient` skips over the `vpython3` stuff, so the `httplib2` library wasn't being installed in the venv.
=> fix: call gclient directly instead of via Python

package.json, yarn.lock
This fixes bugs with option parsing that were making e-cherry-pick break
=> fix: upgrade commander 3.x->9.x

src/e
Closes https://github.com/electron/build-tools/issues/237.
Prevent fallthrough by exiting when config-related commands are passed to `e`.
=> fix: prevent extra argument fall through for configs

src/e-auto-update.js
Fixes an error resultant of https://github.com/electron/build-tools/pull/334 - provide an explicit default action and prevent unknown options from being passed.
=> fix: default auto-update action

package.json, yarn.lock
This reverts commit 7f989cba6fbba1b2d41dbc324d1cf2369d6e5e44.
This brought some unexpected changed and adaptation we weren't aware we needed to make, so let's back this out and do it in another PR to handle e.g:
https://github.com/tj/commander.js/pull/1652
https://github.com/tj/commander.js/pull/1048
=> revert: upgrade commander 3.x->9.x

package.json
Tracked down some testing flakiness due to this. By default, Jest will run each test file in parallel. Since `depot_tools` gets cloned into the source checkout directory, that means each of those parallel test runs are using a single `depot_tools` checkout, creating a race condition depending on the state of that checkout as tests go. I believe that's the root cause of #208, so we can enable macOS CI once this lands.
I also considered changing `DEPOT_TOOLS_DIR` for the sandbox env in `createSandbox`, but that slows down tests significantly since it clones per-test.
You could try to clone `depot_tools` per test file, but running the tests serially like in this PR has little real world impact on test run time, so it seems like the cleanest fix.
@codebytere @ckerr
=> chore: run Jest tests serially

.github/workflows/test.yml
Closes #208. #342 cleared the way for this.
=> chore: run CI for macOS

src/e
Brings it inline with the description in `e-cherry-pick.js`
=> chore: fix typo in description of `e cherry-pick`

package.json, yarn.lock
TL;DR - The version of `fsevents` (being pulled in through Jest) doesn't play nice with Node v17, leading to a `node-gyp` error during install. Bumping the version of Jest to the latest fixes that.
=> chore: upgrade Jest version

src/e-build.js
Not sure if this is fall out from the commander upgrade (seems plausible given the code's usage of `rawArgs`), but currently providing a target argument to `e build` isn't working since it doesn't map it to the correct name.
This tightens up the different ways a target can be provided and I think handles all cases robustly now.
Came from https://github.com/electron/electron/pull/33355 where it was showing up in the wild.
@codebytere
=> fix: properly handle target argument in `e build`

src/e-pr.js
Looks like this got inadvertently broken in #336, so just restoring the previous functionality.
=> fix: make forks work with `e pr` again

package.json
[Commander v9 requires Node 12.20.0+](https://github.com/tj/commander.js/blob/master/CHANGELOG.md#900-2022-01-28)
=> chore: bump Node engine version in package.json

src/e
Commander offers a cleaner way to do this, should be no functional change.
=> chore: don't use program.rawArgs

src/utils/deps-check.js
https://github.com/electron/electron/pull/26186 removed the need for pywin32, so we should remove that dependency check from build-tools
=> chore: remove pywin32 dependency check

.github/workflows/test.yml
Follow-up to #363 to also remove `pywin32` from CI.
=> chore: pywin32 is no longer needed on CI

src/e-cherry-pick.js
Adds support for webrtc and pdfium gerrit links, eg.
https://pdfium-review.googlesource.com/c/pdfium/+/88290
and
https://webrtc-review.googlesource.com/c/src/+/251841
(this latter one necessitating the addition of the host name to the repo name
lookup)
=> feat: support webrtc and pdfium cherry-picks

src/e-load-xcode.js
On new macbooks where Xcode has never been installed before Xcode will not run properly unless the SystemResources package has been installed, this utility ensures it has been installed correctly while running `e load-xcode`
=> fix: install XcodeSystemResources on new macs

src/utils/goma.js
Update to use new goma cluster
- Also fixes #244 because it now uses a newer goma client
=> chore: update to new goma cluster

src/utils/depot-tools.js, src/utils/goma.js, src/utils/xcode.js
Good bye S3 bucket, hello `dev-cdn.electronjs.org.
=> feat: use the new az storage for build tools things

src/utils/xcode.js
Adds support for the new "default" syntax in https://github.com/electron/electron/pull/33905
=> fix: support new xcode version via 'default' value

src/e
Fixes the following error sometimes seen when commands fail:
```
ERROR Failed to run command, exit code was "1", error was 'undefined'
```
=> fix: undefined error message

src/e
Before:
```
ERROR Failed to run command, exit code was "1", error was 'Error: spawnSync python ENOENT'
```
After:
```
ERROR Failed to run command:
Exit Code: "1"
Error: 'spawnSync python ENOENT'
```
Also makes it such that if the exit code is null or there is no error, we don't show them.
=> fix: clean up error messaging a bit

src/e-load-xcode.js
I think these are meant to be `continue`, was poking around in code and they got flagged as `return` statements outside of a func.
=> chore: don't use return statements outside of func

src/e-build.js, src/utils/goma.js
Removes duplicated code and brings it into line with the code in `e-init.js`
There's slight changes in behavior here, namely:
- "Not Authenticated - Triggering Goma Login" will no longer be output from `e build`
- For Goma cluster users, `e init` will now fatal error if the Goma auth process exits with a non-zero status code, which would cause it to bail before building when `--bootstrap` is used. I think this is actually a good thing, as previously that case would have marked the login time down suppressing another attempt for 12 hours, and would have started the build with unauthenticated Goma access
=> chore: refactor to use `goma.auth` in `e-build.js`

src/ci/ci-status.js
Fixes missing CI runs for PRs from forks, e.g. https://github.com/electron/electron/pull/34525 which would show all Appveyor runs as missing.
After:
```
build-tools on git:add-missing-fork-sections ❯ e ci status -r 34418            12:15PM
Ref: refs/pull/34418/head
Circle CI
⦿ macOS - Failed - https://circleci.com/workflow-run/39ccb86c-40f5-44fc-8e4e-855757f53e38
⦿ Linux - Failed - https://circleci.com/workflow-run/80de547f-646c-4ee5-a62f-f9afbd319a9c
⦿ Lint - Failed - https://circleci.com/workflow-run/60aaf76f-1725-405a-8785-92ee70a2d99b
Appveyor
⦿ Windows ia32 - Missing
⦿ Windows i32 (PR) - Success - https://ci.appveyor.com/project/electron-bot/electron-92tg5/builds/43734720
⦿ Windows x64 - Missing
⦿ Windows x64 (PR) - Success - …
```
=> fix: show Appveyor PR runs for forks

src/ci/ci-rerun.js, src/e
Needs rebase when https://github.com/electron/build-tools/pull/379 is merged.
Adds the ability to re-run a given CircleCi Workflow.
```
build-tools on git:add-ci-rerun ❯ e ci rerun 26a85a7a-0c4c-4942-a6e0-5893b0643e18 --from-failed
New Workflow Run
⦿ https://app.circleci.com/pipelines/github/electron/electron/54278/workflows/556a9538-fa82-46ad-94ce-b615b50f1d3b
```
Also tested with https://github.com/electron/electron/pull/34454.
=> feat: add e ci rerun [workflow]

src/ci/ci-status.js
Enable showing individual job status and job IDs for individual checks in `e ci status`.
```
build-tools on git:ci-status-show-jobs ❯ e ci status -s                    10:08AM
Ref: main
Circle CI
⦿ macOS - failed - https://circleci.com/workflow-run/72f39358-9341-4a20-b36a-6220789d44b0
⦿ success mac-make-src-cache, mas-testing-arm64, mas-testing-arm64-tests, mas-testing-x64, mas-testing-x64-tests, mas-testing-x64-gn-check, osx-testing-arm64, osx-testing-arm64-tests, osx-testing-x64, osx-testing-x64-gn-check
⦿ failed - osx-testing-x64-tests - 636701d1-19f4-484d-b23b-995378041905
⦿ Linux - success - https://circleci.com/workflow-run/636344b2-ebd4-49c2-95ce-631ecd548b73
⦿ all jobs succeeded
⦿ Lint - success - https://circleci.com/workflow-run/f3e7db2a-2734-4161-a529-535a2572 …
```
=> feat: enable showing jobs in `e ci status`

src/utils/depot-tools.js, src/utils/goma.js
Run all Goma commands (which use Python) through depot_tools. `python` doesn't exist on the latest macOS (only `python3`), but depot_tools still ships it.
This change actually kicks the Goma client back to using Python 2, but that's OK for the moment since there's some still a case in the client code where it's explicitly calling `python` anyway, which needs to be fixed for a true transition to Python 3.
=> chore: use depot_tools environment for Goma client commands

src/ci/ci-rerun.js
As in title. Follow-up to https://github.com/electron/build-tools/commit/6a81d3ac9b3e58edb6d7181ca87fc09bd3412d36, which only enable rerunning CircleCI workflows.
=> feat: enable rerunning Appveyor builds

package.json, src/e-cherry-pick.js, src/utils/crbug.js, yarn.lock
`e cherry-pick --security` now tries to access the Chromium bug details to fetch the CVE nr. of the vulnerability. The CVE info is then used in the release notes of the security backport PR instead of the Chromium bug nr.
This results in more informative and useful security release notes for Electron users, who are likely to not have permissions to access Chromium security bug details anyway.
Before:
Now:
For this to work, you need to be logged in to crbug.com on Chrome and be a member of the security-notify list. `e cherry-pick --security` will fallback to using the Chromium bug number in the release notes when:
- you're not a member of the security-notify list;
- you're not logged in to crbug.com on Chrome;
- the security vulnerability does not have an associated CVE;
- some other …
=> feat: use CVE nr. in the rel. notes of security backports

src/utils/xcode.js
https://github.com/electron/electron/pull/33905 removed quotes from versions and https://github.com/electron/electron/pull/34850 removed the default config approach, leading to a failure to pick up version:
This fixes the associated regex.
=> fix: xcode parsing from CI config

src/utils/crbug.js
When using `e cherry-pick --security`, if the process that fetches the associated CVE nr. fails, the error handling code crashes due to the usage of `color` without this module having been imported. This change fixes this by importing the `color` module.
=> fix: import required module to eliminate crash

src/e-cherry-pick.js
Addresses #412 .
Adapts the regex matching that is used to parse the bug nr. from Gerrit PRs descriptions, to account for a new variant in how the bug nr. is represented (see example in #412):
- Makes the matching case-insensitive.
- Drops the expectation that a bug nr. following "Bug=" contains the word "chromium".
=> fix: `e cherry-pick` adapt the bug nr. extraction regex for new variant

src/e-build.js, src/utils/depot-tools.js
When you work on multiple projects with different Xcode versions, having `e build` invoke `sudo xcode-select -s` all the time get's annoying.
By setting `DEVELOPER_DIR` in `e-build.js` before calling `e-load-xcode.js`, we make `xcode-select -p` return the correct Xcode path, so `e-load-xcode.js` won't attempt to `xcode-select -s` as sudo. Subsequent subprocess calls to actually build Electron will also pick up that `DEVELOPER_DIR` variable, ensuring that the right Xcode version is used.
```
$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
$ e build
Running "e load-xcode --quiet"
Running "ninja -j 200 electron" in /Users/<user>/electron/master/src/out/Testing
[21/21] STAMP obj/electron/electron.stamp
```
If you actually want to persist the selection change, you can still call …
=> feat: Use DEVELOPER_DIR to set Xcode path without requiring sudo

src/e-build.js, src/e-sync.js, src/evm-config.js
`getDefaultTarget` will trigger a sanitize on the config, leading to the undesirable behavior that `e sanitize-config` will sanitize (and output any problems) twice.
=> refactor: don't run getDefaultTarget on module load

src/e-init.js, src/e-sync.js, src/evm-config.js, tests/e-init-spec.js
This stopped being used a while ago at this point, but it's still in the code base, and changes the remote for `src/third_party/electron_node` in an Electron checkout when it probably shouldn't.
=> chore: remove unused remotes.node in config

src/utils/xcode.js
Quick fix after https://github.com/electron/build-tools/pull/430
Fixes:
```bash
.electron_build_tools on git:main ❯ e load-xcode                                   10:03AM
14.1.0
WARN automatically detected an unknown version of Xcode 4, falling back to default of 14.1.0
SUCCESS
```
=> fix: regexr parsing for Xcode version

src/e-init.js, src/evm-config.js
This speeds up by rebuilds from 8 mintues to 6 minutes on my M1 at least 🤷 seems to be free to enable (only costs local disk space).  Should also reduce load on our clusters from actual devs.
=> build: use the goma local cache by default on init

.github/workflows/lint.yml, .github/workflows/test.yml, package.json
v12 is no longer supported, and I want that sweet, sweet optional chaining.
=> ci: use lts/-1 with actions/setup-node

src/utils/depot-tools.js
While setting up my new Windows laptop, I ran into an error with goma where the `info` command was calling the `python3.bat` file in depot tools, but the `login` command was incorrectly calling just `python3` which is not anywhere in the path on the latest version of Python (3.11) on windows.
This PR follows the same fix as done a little bit below in `depotExecFileSync`: just append `.bat` if the command is `python` or `python3`.
=> fix: goma login on modern python windows

src/e-build.js
Looks like `ninja.exe` was removed in [the commit that dropped ninja binaries](https://chromium.googlesource.com/chromium/tools/depot_tools/+/8f41177abf2c51b2c0114af9abe9a5cd074d5014). `ninja.bat` was added in Nov 2022.
=> fix: use ninja.bat on Windows

.github/workflows/lint.yml, .github/workflows/test.yml
Should clear deprecation warnings on workflow runs.
* Updates and pins SHAs for actions
* Restricts permissions for actions
=> ci: update GitHub actions workflows

src/ci/ci-status.js
Fixes an issue where Appveyor status strings were incorrectly parsed and always displayed `running`.
<details><summary>Before:</summary>
```
electron on git:roller/chromium/main ❯ e ci status                       12:36PM
Ref: roller/chromium/main
Circle CI
⦿ macOS - success - cee1d546-3aaf-4a69-8601-3e89e6a77806
⦿ Linux - success - c85f8742-505c-4d01-880d-03344b510d1f
⦿ Lint - success - f12e8ce8-78f4-4c91-8ea7-9658ff2fa822
Appveyor
⦿ Windows x64 - running - 46084066
⦿ Windows x64 (PR) - Missing
⦿ Windows ia32 - running - 46084053
⦿ Windows ia32 (PR) - Missing
⦿ Windows Arm - running - 46084060
```
</details>
<details><summary>After:</summary>
```
electron on git:roller/chromium/main ❯ e ci status                       12:35PM
Ref: …
```
=> fix: Appveyor status  display

src/e-init.js
[Pointed out](https://github.com/electron/build-tools/commit/bc30071c8ce985c7c32e630677923a599479ecd5#r90654386) by @nornagon, but didn't get fixed before merge.
=> chore: fix name of .goma_output_cache directory

src/utils/goma.js, src/utils/xcode.js
The hash check catches these more or less, but better to be explicit.
=> chore: check for error when downloading Goma/Xcode

src/utils/headers.js
Closes https://github.com/electron/build-tools/issues/465.
=> fix: build node headers without goma when disabled in config

evm-config.schema.json, package.json, src/e-init.js, src/evm-config.js, tests/e-init-spec.js, yarn.lock
Small but interesting change to add `$schema` to configs, referencing the schema on disk. Gets automatic editor support for the config schema in editors that support it like VS Code, and I can drop my duplicate copy of the schema from my VS Code extension. Will otherwise be a no-op.
=> feat: add $schema to configs

src/utils/depot-tools.js
bb70188125f3f0bf21cab1c28a678b4c6b7746af fails lint due to the lack of a trailing comma.
=> chore: fix lint

src/e-test.js
Support for this was added in `e/e` in https://github.com/electron/electron/pull/36944, but the `spec-runner.js` script doesn't have any kind of help output so there's no way to discover that the option is available.
Document it here in the same way that we document the `--runners` option, and just pass it through as-is.
=> chore: document --electronVersion option for test runner

src/e-backport.js
Switching branches may cause pre-commit hooks to fail if you don't do a `yarn install` on the branch.
=> fix: run yarn install on branch in `e backport`

src/e-backport.js
Makes the commands accurate. Pushing to your fork (even if you have write access to `e/e`) is important since `e pr` expects the branch to be on your fork if your config uses one.
=> chore: improve final commands output for `e backport`

evm-config.schema.json, example-configs/evm.chromium.yml
The JSON Schema added in https://github.com/electron/build-tools/issues/421 doesn't take into account a user looking to build Chromium itself.
This fixes that by adding an exception for the required schema objects if the `defaultTarget` is `chrome`.
=> fix: JSON schema Chromium compatibility

evm-config.schema.json, src/e, src/evm-config.js, tests/evm-config-spec.js
Closes #480.
Defaults to being fatal on validation errors, but can also only warn or be disabled entirely (for advanced use cases).
=> feat: per-config validation level

src/e-init.js
Let commander.js handle the validity check for us.
=> refactor: use choices for `e init --goma` option

README.md, src/e
This command spawns your current shell with all the environment variables that build-tools normally uses fully in your environment.  Sometimes I find myself running `e d {thing}` a _lot_ and it's annoying not having things like bash completion or the ability to copy paste commands from chromium docs.
This fixes that by spawning a temporary populated shell with everything you need to run things like `ninja` and `gn` directly.  The extra env var is for folks like me who want to be able to customize their shell prompt when running in this mode, see below for an example.
I was doing this locally with an alias `SHELL_CONTEXT=" $(e show current)" e d $SHELL` but figured other folks might benefit from it
=> feat: add `e shell` command

src/e-auto-update.js
Closes https://github.com/electron/build-tools/issues/414.
Corrects the following error seen in console during auto-update:
```
codebytere@CODEBYTERE-WIN-WORK MINGW64 ~/Developer/electron-gn/src/electron (main)
$ e 
Checking for build-tools updates
'yarn' is not recognized as an internal or external command,
operable program or batch file.
```
=> fix: handle missing `yarn` during auto-update

src/utils/goma.js
`GOMA_FALLBACK_ON_AUTH_FAILURE` is no longer a valid goma client option and is causing errors running gclient
=> ci: remove obsolete goma option

src/e
Useful for when you forget that you turned off auto-update in the past.
=> chore: log info message when auto-update disabled

src/e-test.js
Since an aim of `--electronVersion` is to allow running tests without doing a local build, skip ensuring Node headers exist locally.
=> chore: skip ensure Node headers in `e test` with --electronVersion

src/e-init.js, src/utils/goma.js
Closes https://github.com/electron/build-tools/issues/501.
Fixes an issue where goma would try to perform login when the user was not in cluster mode. Also cleans up some authentication logic and removes an unused export.
<details><summary>Relevant Goma Logic</summary>
<p>
</p>
</details>
=> fix: disable login when goma is `cache-only`

src/ci/ci-status.js
Fixes and cleans up our CI status check logic. It's been broken since we moved to unified AppVeyor on fork and non-fork PRs. 
<details><summary>`main`</summary>
<p>
```
electron on git:main ❯ e ci status                                 3:40PM
Ref: main
Circle CI
⦿ macOS - running - 56aa347f-03bb-4f3d-a2d5-da28a1d0389c
⦿ Linux - running - a7af7126-8397-4b0d-92c3-7cc6d75aa1e4
⦿ Lint - success - 120686f1-5a4e-4a35-8781-caedb852586d
Appveyor
⦿ Windows ia32 - running - 47752802
⦿ Windows x64 - running - 47752803
⦿ Windows Arm - running - 47752801
```
</p>
</details> 
<details><summary>PR #39428</summary>
<p>
```
electron on git:main ❯ e ci status --ref 39428                     3:49PM
Ref: refs/pull/39428/head
Circle CI
⦿ macOS - success - …
```
=> fix: ci status check logic

src/ci/ci-status.js, src/e-backport.js, src/e-cherry-pick.js, src/e-gh-auth.js, src/utils/github-auth.js
Push down the check for `ELECTRON_BUILD_TOOLS_GH_AUTH` into `getGitHubAuthToken` so it won't get missed in future usages of `getGitHubAuthToken`.
Also ensures `e gh-auth` always creates a new token even if the GH cli already has one.
=> refactor: check GH auth token env var in getGitHubAuthToken

src/utils/github-auth.js
The `gh auth token` command was added a while back in https://github.com/cli/cli/pull/6324, so use that to simplify this code.
=> refactor: use gh auth token instead of parsing gh auth status

src/e-build.js, src/evm-config.js
- https://github.com/electron/electron/pull/39589 changed the node headers target.  This PR updates build-tools to the new target and also provides a fallback to the old target for older versions of Electron.
- Fixes #511
=> chore: update node headers target

src/e, src/e-depot-tools.js, src/utils/depot-tools.js
Allow disabling automatic depot-tools updating - I hit this on the plane on the way over. We call it ourselves but it's also called in some other cases so I took the marker-file approach that [depot_tools understands](https://chromium.googlesource.com/chromium/tools/depot_tools/+/248aa8ba818b752ef507c73db988b6d32bb90df1/update_depot_tools#31) to cover all bases.
=> feat: allow disabling `depot_tools` auto-update on sync

src/utils/depot-tools.js
Refs #522 and #493.
It's easy to forget you disabled auto-updates in the past, an info message is useful to prevent any confusion.
=> chore: log info message when depot_tools auto-update disabled

src/e, src/utils/depot-tools.js
Outputting to stdout breaks commands like `` cd `e show exec` ``, so use stderr instead.
Fixes: 700187712658e6fbdf521aac1a3ca6e8de8f0f2d ("chore: log info message when auto-update disabled")
=> fix: send "Auto-updates disabled" messages to stderr, not stdout

.github/workflows/lint.yml, .github/workflows/test.yml
Bumps versions to get things off EOL Node.js versions and preempts deprecation warnings.
=> ci: update workflows

evm-config.schema.json, package.json, src/download.js, src/e-build.js, src/e-depot-tools.js, src/evm-config.js, src/utils/depot-tools.js, src/utils/reclient.js, tests/evm-config-spec.js, yarn.lock
This isn't fully ready for public consumption but putting it up now for others to see.  Some missing pieces:
* ~~A more developer friendly way of getting auth onto the machine~~ `e d rbe login`
* ~~Either a more generic hack for https://github.com/bazelbuild/reclient/issues/27 or a real fix upstream~~ Moved TLS termination out of nginx and instead the RBE frontend
* No idea if this even remotely works on windows
* Needs some changes to `e/e` as well https://github.com/electron/electron/pull/40850
=> feat: add support for reclient

src/evm-config.js
Follow-up to #533, the log messages don't match the final config key name.
=> chore: fix log messages for reclient config changes

src/e-auto-update.js
Users don't need dev dependencies. By not installing them the size of `node_modules` in `.electron_build_tools` goes from 207 MB to 57 MB on my machine.
=> chore: don't install dev dependencies when updating

tests/sandbox.js
`vpython` has updated to being written in Go upstream, and now throws an error during tests if the user's home directory can't be determined via environment variables.
Refs https://github.com/golang/go/blob/b2dbfbfc2315557815e1d5de12f28ed57f60958a/src/os/file.go#L445-L494
=> test: set user home environment variables in sandbox

evm-config.schema.json, example-configs/evm.base.yml, example-configs/evm.chromium.yml, src/e-init.js, tests/e-init-spec.js, tests/sandbox.js
As in title, init should use reclient now
=> feat: use reclient on init instead of goma

src/e-build.js, src/e-test.js, src/utils/headers.js
Rename `--no-goma` to `--no-remote` so that one option works for either Goma or Reclient, and we'll just rip out the Goma code in the future once Goma is no longer supported.
=> feat: rename --no-goma option to --no-remote

src/evm-config.js
I think we can safely remove handling for this as its been several years since it was last relevant.
=> chore: remove sccache config handling

evm-config.schema.json, example-configs/evm.base.yml, src/e, src/e-init.js, src/evm-config.js, src/utils/xcode.js, tests/evm-config-spec.js
Closes https://github.com/electron/build-tools/issues/539.
Adds a new config preference to optionally delete unused Xcode versions to save disk space.
=> feat: allow deleting old Xcode versions

src/e-cherry-pick.js
A recent change to the cherry-pick script includes a typo which tries to call the number `6` as a function.
I also took the liberty to simplify the code using the [Optional chaining operator `?.`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) which has been stable in Node.js since v14 (4 years ago).
=> fix: cherry-pick script

src/e-patches.js
Changes to `e patches`:
1. Support passing in a custom patches config file instead of always using `electron/patches/config.json`
2. Add support for a `config.json` formatted as an array of objects with `patch_dir` and `repo` properties and an optional `grep` property.
This goes hand-in-hand with https://github.com/electron/electron/pull/41174 for more information; see that PR for more information.
CC @mlaurencin, @jkleinsc
=> feat: support custom patches config file location

package.json, src/utils/goma.js, src/utils/paths.js, src/utils/reclient.js, src/utils/xcode.js, tests/e-update-goma-spec.js, tests/sandbox.js
`rimraf` was pulled into Node.js core in v14, and we can use native `fs` methods to achieve the same end, e.g. `rimraf.sync(path)` -> `fs.rmSync(path, { force: true, recursive: true })`
=> refactor: remove rimraf usage

src/e-auto-update.js
I noticed build-tools pulling down branches which aren't relevant to most users. I've changed auto-update to only pull down main/master.
```
% e build
Checking for build-tools updates
Running "git pull --rebase --autostash" in /Users/samuelmaddock/.electron_build_tools
From https://github.com/electron/build-tools
dad2c81..c92af31  debug/ci   -> origin/debug/ci
build-tools is up-to-date
```
=> fix: only auto-update main branch

evm-config.schema.json, src/e-depot-tools.js, src/utils/reclient.js
This PR adds two configs to allow use of an alternative RBE cluster with build tools:
* **reclientHelperPath** - Path to alternative reclient credential helper. When using this option, build-tools will assume that the helper is already properly installed at the specified path.
* **reclientServiceAddress** - Alternative RBE cluster address
=> chore: add support for alternative RBE cluster and helper

src/utils/depot-tools.js
Adding support for [New toolchain for Windows 11 10.0.22621.2428 SDK](https://chromium-review.googlesource.com/c/chromium/src/+/5350823) to build-tools
=> chore: update windows toolchain

src/e-init.js, src/e-sync.js, src/utils/load-xcode.js, tests/e-init-spec.js, tests/sandbox.js
=> fix: load xcode before `e init` 

README.md
=> docs: add backport description

package.json, yarn.lock
Closes https://github.com/electron/build-tools/issues/577.
Standardize on a version of semver.
=> build(deps): add semver to package.json

src/utils/xcode.js
`.circleci/build_config.yml` was removed in https://github.com/electron/electron/pull/33881, which landed two years ago and shipped in E20. Seems safe to remove this.
=> chore: remove legacy check for build_config.yml

src/utils/depot-tools.js, src/utils/refresh-path.js, tests/sandbox.js
Refs https://github.com/nodejs/node/issues/52554
After the latest security fix on Node.js on Windows, spawning `.cmd` files is blocked unless `{ shell: true }` is used.
=> fix: EINVAL when spawning on Windows

src/e-init.js, src/e-sync.js, src/utils/xcode.js
Managed to break my Windows checkout in ✨ New and Exciting Ways ✨ while trying to get it out of a bad state.
As a result of debugging how it had gotten so bungled, found there are a handful of cases where the status code from `spawnSync` isn't being checked, so this tightens those down for good measure so it doesn't create more problems if those commands fail.
This also adds a check to confirm that it's setting git remotes in the expected git repo, as one of the exciting ways my checkout broke was the remotes on `src/` were overwritten to point to `electron/electron.git`. Some combination of `e sync` failing leaving `src/` unpatched, then a following `e sync -D` tried and failed to remove `src/electron` but did manage to remove `src/electron/.git` so the subsequent `git remote` calls in …
=> fix: check for errors in more places

src/e-build.js
Fixes #582.
With the changes in #581, a shell is now being used to execute `gn.bat` on Windows and as a result the GN arguments are no longer interpreted correctly (due to spaces between arguments). Seemed simplest to dump them directly into `args.gn` rather than escape quotes and potentially miss some corner cases.
=> fix: output directly to args.gn

src/e-pr.js
We should gracefully handle `e pr` being called in a non-electron repo.
<details><summary>Details</summary>
<p>
```
.electron_build_tools on git:main ❯ e pr                                       5:55PM
fatal: No names found, cannot describe anything.
node:child_process:915
throw err;
^
Error: Command failed: git describe --tags `git rev-list --tags --max-count=1`
fatal: No names found, cannot describe anything.
at checkExecSyncError (node:child_process:841:11)
at Object.execSync (node:child_process:912:15)
at guessPRTarget (/Users/codebytere/.electron_build_tools/src/e-pr.js:72:6)
at Object.<anonymous> (/Users/codebytere/.electron_build_tools/src/e-pr.js:140:5)
at Module._compile (node:internal/modules/cjs/loader:1126:14)
at Object.Module._extensions..js …
```
=> fix: handle e pr from wrong repo

src/e, src/e-auto-update.js
We shouldn't check for updates by default if we've set `BUILD_TOOLS_SHA` in order to pin to a sha.
Also fixes an issue where build-tools being checked out on a sha resulted in a broken error:
```
ERROR build-tools is checked out on   and not 'main' - please switch and try again.
```
=> fix: skip update when BUILD_TOOLS_SHA is set

src/e-build.js, src/e-init.js
Allows extending information present in `config.gen.args` with `GN_EXTRA_ARGS` env var. This shouldn't be commonly used but will allow us to remove config files present in the GHA pipelines and avoid some unnecessary duplication.
=> chore: allow extending `config.gen.args` with env var

src/e
We don't need the extra check and it introduces potential issues: https://github.com/electron/electron/actions/runs/9455995083/job/26047569839
=> fix: just check for `BUILD_TOOLS_SHA`

evm-config.schema.json, example-configs/evm.chromium.yml
Fixes using `e start` with stock Chromium. `execName` is already supported: https://github.com/electron/build-tools/blob/2f67e10b9b6b5700b1c7940df412b0345257d9ae/src/evm-config.js#L125-L137
But wasn't in the schema.
=> fix: e start with Chromium

src/utils/sdk.js
Fixes this:
```
electron on git:main ❯ e build                                          3:11PM
INFO Now using SDK version 14.0
INFO Now using SDK version 14.0
INFO Now using SDK version 14.0
Running "/Users/codebytere/.electron_build_tools/third_party/depot_tools/gn gen out/Testing" in /Users/codebytere/Developer/electron-gn/src
Done. Made 21537 targets from 3721 files in 11785ms
Running "autoninja -j 200 electron" in /Users/codebytere/Developer/electron-gn/src/out/Testing
Proxy started successfully.
[0/1] Regenerating ninja files
[22/22] STAMP obj/electron/electron.stamp
RBE Stats: down 0 B, up 0 B, 1 racing local
```
=> fix: only notify SDK when changed

src/utils/load-xcode.js, src/utils/xcode.js
Refs https://github.com/electron/electron/pull/42763.
We shouldn't be using the CircleCI config files to fetch the XCode version necessary for build now they've been removed - use `src/build/mac_toolchain.py` in Chromium only. This is also what we're doing for the associated SDK logic.
=> fix: don't use CircleCI config to find Xcode version

src/utils/sdk.js, src/utils/xcode.js
Refs https://github.com/electron/build-tools/pull/612
On `e init`, we won't have the source files yet and so `src/build/mac_toolchain.py` won't exist. Use the default Xcode or SDK in this event. Also tighten up some error handling here.
=> fix: mac_toolchain.py won't exist on init

src/evm-config.js
We're using `_.mergeWith` in this file without importing it.
https://github.com/erickzhao/build-tools/blob/8c95e2259a1085362b6e78fdffb88480c28d6e49/src/evm-config.js#L144-L148
=> fix(evm-config): import `lodash`

README.md
- Followup for #627.  Adds a small bit of documentation for `e d`
=> chore: document `e d`

src/utils/reclient.js
For cache only reclient, we should set the following environment variables:
RBE_fail_early_min_action_count: '0',
RBE_fail_early_min_fallback_ratio: '0',
RBE_exec_strategy: 'local',
RBE_remote_update_cache: 'false'
This PR uses the new `flags` command on rbe-credential-helper to get these environment variables
- Fixes #630
=> chore: set additional RBE flags when using read only reclient

src/utils/reclient.js
Handle failure gracefully:
```
SyntaxError: Unexpected token U in JSON at position 0
at JSON.parse (<anonymous>)
at Object.reclientEnv [as env] (reclient.js:112:28)
```
=> fix: handle reclient helper failure gracefully

src/e-sync.js, src/utils/setup-reclient-chromium.js, tools/engflow_reclient_configs.patch
Enables building stock Chromium more simply.
Patches are applied now upon sync when targeting Chromium, with reduced area for failure with pinned `EngFlow/reclient-configs` sha.
=> feat: streamline using Reclient for Chromium

README.md, src/e-build.js, src/e-sync.js, src/evm-config.js, src/utils/load-xcode.js
This PR adds some improvements to the `e build` documentation to clarify passing `--target` as well as how to see/use possible build targets.
=> docs: improve e build --target documentation

src/utils/setup-reclient-chromium.js, tools/engflow_reclient_configs.patch
bumps to https://github.com/EngFlow/reclient-configs/commit/7851c9387a770d6381f4634cb293293d2b30c502
=> chore: bump engflow-reclient-configs

src/e-cherry-pick.js, src/utils/crbug.js
Allows continuing to create the PR if CVE parsing fails in Chromium's Issue Tracker:
```
electron on git:30-x-y ❯ e cherry-pick --security https://chromium-review.googlesource.com/c/chromium/src/+/5402199 30-x-y
WARN Failed to fetch CVE for 330756841 - you'll need to find it manually
```
=> fix: handle `getCveForBugNr` failure

evm-config.schema.json, src/e-test.js, src/utils/headers.js
Refs https://github.com/electron/build-tools/pull/635
Fixes broken `e test` with old header alias.
=> fix: e test after aliases change

src/utils/github-auth.js
Fixes an issue where I would be repeatedly asked for token authentication despite authenticating successfully previously.
This was rooted in two issues:
1) `String.prototype.match()` won't return capture groups if the `g` flag is set - so the result of the `match` was an array with one value: `[ "- Token scopes: 'gist'", "'read:org'", "'repo'", "'workflow'" ]`
2) The quotes weren't being parsed out correctly, so the scopes were being checked as `"'read:org'"` instead of `read:org` which would incorrectly return false.
After this change, `tokenScopes` is `[ 'gist', 'read:org', 'repo', 'workflow' ]` as expected, which prevents the issue.
=> fix: `getGitHubAuthToken` scope handling

src/utils/sdk.js
Fixes the regex to match all recent formats seen in `build/mac_toolchain.py`
```py
```
```py
```
```py
```
In this above, we would successfully parse 13, 14.0, and 15.0 as 13.0, 14.0, and 15.0.
=> fix: macOS SDK parsing regex

src/e-backport.js
This fixes an issue I keep running into where I run `e backport` immediately after merging the original PR, it bails because the sha it's trying to cherry pick isn't local yet because I haven't run `git fetch` or `git pull` for the base ref.
=> fix: fetch latest base ref to ensure merge sha is local

src/utils/reclient.js
Upstream will pick https://github.com/bazelbuild/reclient/commit/4017a6c8b46c6ad9cd15932d97607a4065a9b26a up soon and when they do we want build tools to keep working.
=> fix: reclient support for non-experimental cred helper

src/e-init.js, src/e-sync.js, src/utils/sdk.js
This nicely handles the user not having a full xcode install (and just command line instead). Tested / written while setting up my new laptop 😅 
This also ensures that during `e init` if we hard bail for Xcode we do it as early as possible.
=> feat: handle sdk-only clean set up without xcode

src/utils/reclient.js
Fixes the following seen when building Chromium with build-tools:
```
reclient[f2fe214d-088a-45ba-a536-22bed7df2d61]: LocalErrorResultStatus: this build has encountered too many local fallbacks. This means that the ratio of actions that failed remotely is equal to or above the preconfigured threshold of 50.0%
```
=> fix: early RBE failure building Chromium

src/utils/sdk.js
Addresses https://github.com/electron/build-tools/pull/617#pullrequestreview-2175557963.
Throws a descriptive error if the system Xcode version is too old. We should make this more dynamic to the current OS version but this should be enough for now.
=> fix: handle outdated system Xcode version

src/utils/reclient.js
Temporary fix to get reclient read only cache working on fork PRs
=> chore: fixup reclient read only access on forks

src/e-init.js
- #653 broke e init on a fresh install on macOS because `ensureSDK` needs a current config written before running.  This fixes that error.
=> chore: fix ensureSDK when calling e init for the first time

src/e-cherry-pick.js
Follow-up to #643, this is currently throwing a `TypeError` since it's destructuring an object into an argument list.
=> fix: cherry-pick command

src/e-build.js, src/e-sync.js, tests/sandbox.js
This is redundant after https://github.com/electron/build-tools/pull/617.
The only place this should be checked is config sanitization.
=> fix: remove `onlySdk` checks

src/e-cherry-pick.js
This simplifies nicely using `fetch`. Also replaces the usage of `got` in this file with `fetch`.
=> refactor: use fetch in e-cherry-pick.js

src/e-build.js
`getGNArgs` is called miltiple places in the codebase, and we weren't checking to see if the sdk path was added already, which resulted in it being duplicated:
```gn
import("//electron/build/args/testing.gn")
use_remoteexec=true
mac_sdk_path = "//out/Testing/xcode_links/electron/MacOSX15.0.sdk"
mac_sdk_path = "//out/Testing/xcode_links/electron/MacOSX15.0.sdk"
```
This fixes that
=> fix: mac_sdk_path double-adding

src/utils/sdk.js
`build/mac_toolchain.py` won't exist during initial `e init` - log that information as opposed to saying an unknown version was detected, since that's expected.
Refs https://github.com/electron/build-tools/issues/669.
=> refactor: show slightly better sdk error during init

src/utils/depot-tools.js
I think it is reasonable for _**local development only**_ that use local VS instead of downloading a huge blob from electron's cdn.
This indeed benefits binary consistency and CI, but seems not important for contributors to develop locally, so perhaps we can disable it by set `ELECTRON_DEPOT_TOOLS_WIN_TOOLCHAIN` to `0`, since this feature is kind of hidden, the developer knows what they are doing.
Even in [official docs](https://www.electronjs.org/docs/latest/development/build-instructions-gn#gn-prerequisites) wants contributing developers to use local toolchain instead of downloading, so I think it should be all right to disable here.
=> fix: allow disable download windows toolchain on windows platform

src/e-build.js
https://github.com/electron/build-tools/pull/674#issuecomment-2460795510
=> feat: disable reclient when defined `ELECTRON_DEPOT_TOOLS_WIN_TOOLCHAIN=0` on windows.

src/utils/sdk.js
Ref https://chromium-review.googlesource.com/c/chromium/src/+/5973484
This wasn't updated in the corresponding Chrome roll that pulled it in.
=> chore: add new macOS 15.1 SDK

src/utils/depot-tools.js
The windows toolchain CDN occasionally has issues, eg see: https://ci.appveyor.com/project/electron-bot/electron-woa-testing/builds/51151443/job/ligpcjoi562bw1ao, so instead use a non CDN location for the windows toolchain.
=> chore: use alternate location for windows toolchain

src/e-debug.js
Ensures `e debug -h` outputs useful output instead of launching into the command
=> chore: enable help option for e debug

src/utils/setup-reclient-chromium.js
Without this step building Chromium will result in the following error:
```
src on git:main ❯ e build
Running "autoninja -j 200 chrome" in /Users/codebytere/Developer/chromium/src/out/Default
You can't use rbe-chrome-untrusted on non-corp machine.
Please use rbe-chromium-untrusted and non-@google.com account instead to build chromium.
ERROR Error: Command failed: autoninja -j 200 chrome
```
cc @dsanders11
=> fix: RBE untrusted step for Chromium building

src/e-backport.js, src/e-init.js, src/e-sync.js, src/utils/depot-tools.js, src/utils/setup-reclient-chromium.js
Makes the code more DRY and removes the need for all the intermediate variables cluttering things up.
=> refactor: add optional fatal message to depot-tools spawnSync

src/utils/sdk.js
Refs https://chromium-review.googlesource.com/c/chromium/src/+/6312080 - the format changed subtly and so detection broke:
> WARN Automatically detected an unknown macOS SDK - falling back to default of 15.2
=> fix: macOS SDK detection regex

README.md
Fixes #704
(I don't think I can verify that the list of permissions is correct. I took it from [here](https://github.com/electron/build-tools/issues/704#issuecomment-2737529073). Would be great if someone could make sure my wording represents reality.)
=> docs: add note about reclient permissions

src/e, src/e-cherry-pick.js, src/e-rcv.js, src/utils/gerrit.js
Also goes by its less wordy name, `e rcv`. Aims to automate the process of bisecting into a Chromium roll PR by "reconstructing" an intermediate Chromium version of your choice via cherry-picking the relevant PR commits (thanks to our consistent style of including the relevant CL in our commit messages).
=> feat: reconstruct-chromium-version command

src/utils/depot-tools.js
This is effectively dead code these days, `python_bin_reldir.txt` doesn't exist now that everything uses Python3 (`python3_bin_reldir.txt` does) so it's never going to succeed with a modern `depot_tools` checkout, and Python3 works fine.
=> chore: remove outdated Python2 workaround for Apple Silicon

tests/e-init.spec.mjs
This test loves to timeout in CI on Windows, so give it 10 minutes so it'll stop creating noise. 😬
=> test: bump timeout for e-init --root test

src/e-rcv.js
As in title, and we don't want to attribute the commits to the user's git identity anyway since they're just commits on a temporary branch.
=> chore: make e-rcv work without a configured git identity

.github/workflows/test.yml, src/utils/git.js
This has hit contributors semi-regularly for years - we should make it default.
=> fix: set `core.longpaths` on Windows by default

evm-config.schema.json, example-configs/evm.base.yml, example-configs/evm.chromium.yml, src/e-build.js, src/e-depot-tools.js, src/e-init.js, src/evm-config.js, src/utils/depot-tools.js, src/utils/reclient.js, src/utils/sdk.js, src/utils/siso.js, tests/e-init.spec.mjs, tests/evm-config.spec.mjs
This PR does a few things:
* Sets up basic SISO env vars and flags for the build command (and other depot tools commands)
* Migrates a bunch of `reclient*` config options to `rbe*` or just `remoteBuild` to make it clear these are tool agnostic and work for anything consuming RBE in the electron build system
Default is still `reclient`, and `siso` doesn't work yet (so please don't try it)
=> feat: add siso configuration support

src/download.js
Ref https://github.com/electron/build-tools/pull/734
The above surfaced some rathe subpar download handling:
```
electron on git:main ❯ e build                                         9:21PM
Downloading "https://dev-cdn-experimental.electronjs.org/reclient/credential-helper/v0.5.1/electron-rbe-credential-helper-darwin-arm64.tar.gz" into /Users/codebytere/.electron_build_tools/third_party/reclient.tar.gz
404 The specified blob does not exist.
/Users/codebytere/.electron_build_tools/node_modules/progress/lib/node-progress.js:160
complete = Array(Math.max(0, completeLength + 1)).join(this.chars.complete);
^
RangeError: Invalid array length
at ProgressBar.render (/Users/codebytere/.electron_build_tools/node_modules/progress/lib/node-progress.js:160:14)
at ProgressBar.tick …
```
=> chore: improve error handling on failed download

src/e-rcv.js
Sometimes roll PRs end up with a lot of commits, the current one has 65 and counting. Use pagination to ensure we get all of the commits.
=> fix: paginate commits in e-rcv
