electron/build-tools

nix/commands/__constants.sh
nix/commands/bootstrap.sh
nix/commands/build.sh
nix/commands/fetch.sh
nix/commands/sync.sh

does what it says in the title: adds color to the nix log messages similar to our chalk messages in js scripts

feat: on nix, add chalklike color-coded messages

---

.github/workflows/lint.yml
.gitignore
.shellcheckrc
nix/commands/__load-env.sh
nix/commands/__tools.sh
nix/commands/export-patches.sh
nix/e
package.json

What it says on the tin. Add a lint check for bash code. To enable this, i needed to correct some of our bash to align with shellcheck expectations.
cc @MarshallOfSound @ckerr

chore: add shellcheck linting

---

nix/commands/__tools.sh
nix/commands/bootstrap.sh
nix/commands/build.sh
nix/commands/fetch.sh
nix/commands/sync.sh
yarn.lock

This PR adds a couple of little helper functions so that each log message doesn't have to manually reset the colors after the displaying the highlighted text.
A minor PR that I did on the side while testing asan. Split into a standalone PR for cleanliness.

refactor: simplify logging with colors

---

example-configs/evm.base.yml
example-configs/evm.debug.yml
example-configs/evm.release.yml
example-configs/evm.testing.yml

Adds some example config files for reference.

chore: add some example config files

---

src/e

fix: logs were being ignored

---

README.md

A follow-on to the previous PR to address the suggestions made by @codebytere

docs: explain powershell and cmd

---

.github/workflows/ISSUE_TEMPLATE/bug_report.md

chore: add issue template for bugs

---

src/utils/depot-tools.js
src/utils/macos-sdks.js
src/utils/xcode.js

When these got moved a folder deeper the paths didn't get updated, TLDR we need tests lol

fix: use correct third_party path from the utils folder

---

src/e

fix: quick argument sanitization for 'e d'

---

package.json
yarn.lock

I hate lint, plz no more lint failures

build: set up lint-staged to make linting painless

---

src/e-build.js

For building other projects or just more specific custom targets in Electron.
This also adds support for a new `defaultTarget` config so that other projects can specify what target gets built when you just run `e build`

feat: add support for custom ninja target

---

src/e-init.js
src/utils/git.js

Closes https://github.com/electron/build-tools/issues/81.
Ensure global git settings are correct on windows; throw an error if they are not correctly set.
cc @MarshallOfSound @ckerr

fix: check some global git settings on win32

---

src/utils/git.js

Fix for work introduced in #81. Came across this while fixing another issue. 🙂

fix(git): use 'core.filemode' config

---

README.md

Fixes markdown formatting in readme

fix(readme): patch table formatting

---

src/utils/git.js

Ref #81. Should be `always` but error message want `false`

docs: fix requested value of branch.autosetuprebase

---

src/e-build.js

fix: gn args file uses platform specific line endings

---

src/evm-config.js

fix: handle the configs folder not existing

---

src/e-load-xcode.js

We should only be linking 10.14 & 10.15, as older ones now cause compilation errors.

fix: only load newer macOS sdks

---

src/e-load-xcode.js
src/utils/xcode.js

No more `sudo ln` and improves the logging around `load-xcode`

chore: do not use sudo to link SDKs and improve logging

---

src/e-build.js
src/e-load-xcode.js
src/utils/depot-tools.js

As in title, on macOS let's load the right xcode version auto-magically

feat: automatically load the right xcode version

---

src/e-build.js
src/e-init.js
src/e-test.js

fix: use process.execPath instead of looking up node on the PATH

---

package.json
src/e
src/e-init.js
src/e-sync.js
src/utils/depot-tools.js
src/utils/deps-check.js
src/utils/get-path.bat
src/utils/git.js
src/utils/maybe-auto-fix.js
src/utils/refresh-path.js
src/utils/which.js
yarn.lock

This makes the windows set-up experience and self-fixing one-click wonder-experience.
I just set up a new VM by installing git and node and then just ran `e init` and everything just sorted itself out, no need for Visual Studio or python or pywin32 nonsense.  Build tools sets up the entire toolchain

feat: better windows, well, everything

---

src/utils/xcode.js

chore: add xcode 11.5 support

---

src/utils/arm.js
src/utils/xcode.js

Otherwise, we'll try to use a version of Xcode that doesn't run on Apple Silicon.

fix: Don't download Xcode on ARM

---

src/utils/xcode.js

fix: update reference to arm

---

src/e-pr.js

String coercion,,,,,,how does it work,,,,,,,

fix: don't compare number to string

---

src/e
src/e-build.js
src/e-init.js
src/utils/goma.js

fix: smoothly stop goma before updating it

---

src/e-check-for-updates.js
src/utils/arm.js
src/utils/xcode.js

This is a small cleanup PR to fix a few "unused code" warnings. No functional changes.

chore: remove unused code

---

src/utils/xcode.js

For `master` / `11-x-y` compatibility 🤔

build: add support for Xcode 12.2.0

---

src/e-check-for-updates.js
src/e-debug.js
src/e-init.js
src/e-open.js
src/evm-config.js
src/utils/deps-check.js
src/utils/goma.js
src/utils/which.js
src/utils/xcode.js

For the errors below, it won't benefit the user to see the full stacktrace. As such, just log a colorized error and exit the process.
cc @ckerr

chore: cleaner user error messages

---

src/e-sync.js

Fixes an issue whereby `setRemotes` would _always_ try to update the remote URLs, prior to fork remote creation. This adds a check to instead create the fork remote if it does not exist yet.

fix: create fork remote if none exists yet

---

tests/e-show-spec.js

Forgot to update the tests with #204.

fix: use set keyword in show env tests for Windows

---

.github/workflows/lint.yml
.github/workflows/pull_request.yml

Run CI on all the platforms... except MacOS for tests.
Couldn't get the MacOS tests to pass on CI, if anyone else wants to take a look.

chore: run CI on all platforms

---

src/e-show.js

For easy programmatic access to the environment.

feat: --json flag for `show env` command

---

src/e-show.js
src/utils/depot-tools.js
tests/e-show-spec.js

Per discussion on Slack the other day. @MarshallOfSound, is this what you were thinking?

feat: show full depot_tools env

---

src/e-pr.js

Figures out the proper URL for a PR from a branch on a fork, and supports sources branch names of the form `fork/foobar`.

feat: support forks in `e pr`

---

src/e-build.js

Refs #229.
Sometimes it's better to not use Goma, like when you don't have Internet access. Provides a flag to toggle Goma at build-time rather than needing to modify your config and change it back.

feat: --no-goma flag for `e build`

---

src/utils/depot-tools.js

Turns out this is all we needed 😄

feat: add support for building Electron on Apple silicon

---

src/e-build.js
src/utils/goma.js

feat: add experimental one-for-all goma cluster support

---

src/e-sync.js

Setting the env var manually is annoying `e sync --3`

feat: add e sync --three-way flag

---

src/e-build.js
src/utils/goma.js

feat: use one-for-all goma cluster for everyone

---

src/e
src/utils/goma.js

This PR adds support for the Microsoft Goma cluster for those who have access to that cluster.

chore: add support for Microsoft Goma cluster

---

src/utils/goma.js

Clean up arg passing to platform-specific processes.

refactor: clean up goma arg params

---

src/utils/xcode.js

chore: add Xcode-12.4.0 support

---

package.json
src/e-cherry-pick.js
src/utils/github-auth.js
yarn.lock

Instead of making folks figure out github tokens and environment variables, let's use device-code based auth.

chore: use github device auth for github API requests

---

README.md
src/e-pr.js
tests/bootstrap-spec.js
tests/e-init-spec.js
tests/sandbox.js

As in title, land when the migration happens

chore: migrate to the main branch for e/e

---

README.md

* Backtick proposals (lines 154, 250)
* semantic issue (line 419)

docs: copyediting README - Backtick proposal (line 44)

---

src/e-show.js
tests/sandbox.js

Miscellaneous cleanup discovered when attempting to write a https://fig.io/ config for `build-tools`

refactor: cleanup e-show

---

src/e-auto-update.js

We currently can't rename build-tools' primary branch from `master` to `main` because it will break auto-updating.
This PR checks to see if `main` exists at origin. If so, it asks the user to switch to `main` instead of the current behavior of asking the user to switch to `master`.
So we can merge this, then wait a while for users to get auto-updated with this code, and then rename the primary branch.

feat: auto-update support of 'main' branch

---

src/utils/xcode.js

feat: add Xcode 13.2.1

---

src/utils/xcode.js

refactor: fallback to latest XCode version

---

.github/workflows/lint.yml
.github/workflows/test.yml

Consequent to https://github.com/electron/build-tools/issues/332.

test: fix target branch

---

src/e

Follow up to the `master`->`main` transition.

chore: update README link in help output

---

src/utils/depot-tools.js

Closes https://github.com/electron/build-tools/issues/360
Pulls in https://chromium-review.googlesource.com/c/chromium/src/+/3550827

chore: handle Windows toolchain updates

---

src/e-build.js

fix: --gen option for `e build`

---

src/e-show.js

After upgrading Commander to v9, this seems to work as intended without this code being necessary.

chore: remove unneeded code

---

src/utils/github-auth.js

The `gh` cli has a readable token. Use that to create PRs if available.

feat: get gh token from gh cli if available

---

src/utils/goma.js

chore: fixup msft goma_auth for python3

---

src/e-ci.js

Before, if I ran `e ci status` for a branch I hadn't pushed yet, i'd see the following:
```
/Users/codebytere/build-tools/node_modules/@octokit/request/dist-node/index.js:68
const error = new requestError.RequestError(message, status, {
^
RequestError [HttpError]: No commit found for SHA: dd39c652a79fcacca4a9e3afcc4036f58d9b2a84
at /Users/codebytere/build-tools/node_modules/@octokit/request/dist-node/index.js:68:23
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Command.<anonymous> (/Users/codebytere/build-tools/src/e-ci.js:41:9) {
status: 422,
headers: {
'access-control-allow-origin': '*',
'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, …
```

fix: better error messaging for bad shas in e-ci

---

src/ci/ci-status.js
src/e
src/e-backport.js

Updates `e ci` to allow printing status for an arbitrary ref and not just the ref for the current checkout.
Also refactors into discrete Ci subcommands in preparation for a further PR to allow rerunning CI from `build-tools`
Examples 
For PR:
```
build-tools on git:check-specified-branch ❯ e ci status -r 34454                       10:41AM
Ref: refs/pull/34454/head
Circle CI
⦿ macOS - Success - https://circleci.com/workflow-run/5520d17a-37eb-45fc-b981-642c798fa511
⦿ Linux - Failed - https://circleci.com/workflow-run/86ddd426-cc94-4337-a8dd-dd8cfbc1465c
⦿ Lint - Success - https://circleci.com/workflow-run/f98a5979-47f7-4139-851c-20045fea0dff
Appveyor
⦿ Windows ia32 - Success - https://ci.appveyor.com/project/electron-bot/electron-ia32-testing/builds/43775055
⦿ Windows …
```

feat: check CI status for arbitrary ref

---

src/utils/goma.js

Accidentally broke this in #381.

fix: make Goma login work again

---

src/download.js
src/e
src/e-load-xcode.js
src/e-patches.js
src/utils/goma.js
src/utils/logging.js

Added ability to give `fatal` an exit code to use, and spread `fatal` around to more places in the code base.
Marking this as WIP until #381 lands so that I can change that usage as well.

chore: use `fatal` in more places

---

src/ci/ci-rerun.js

Allows rerunning specific jobs within a workflow, as well as rerunning with SSH enabled.

feat: allow rerunning specific workflow jobs

---

src/evm-config.js

fix: correct name for breakpad build target

---

src/ci/ci-status.js

As in title. Show CI info for Azure Pipelines.

feat: show VSTS pipelines check status

---

src/ci/ci-status.js

Closes https://github.com/electron/build-tools/issues/389.
Take advantage of smart linking (see [here](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda)) to improve terminal output. Also include optional switch to disable in case a user doesn't have this capability in their terminal.
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>

feat: add smart escape sequencing to ci status

---

src/ci/ci-status.js

We've switched this to GitHub Actions.

chore: remove unused VSTS check

---

.github/CODEOWNERS

chore: add @jkleinsc as a CODEOWNER

---

src/ci/ci-rerun.js

Allow rerunning Appveyor builds from last failed step. Enabled by https://github.com/electron/electron/pull/35377.

feat: allow rerunning Appveyor builds from failed

---

src/ci/ci-cancel.js
src/ci/ci-rerun.js
src/ci/common.js
src/e

Closes https://github.com/electron/build-tools/issues/404.

feat: enable cancelling workflows/builds

---

src/e-auto-update.js

Soliciting feedback on this one. Got a chicken-and-egg problem and trying to minimize breakage for folks. electron/build-tools-installer#6 landed and adds the long-form `electron-build-tools` which is 'safer' to use for working with `build-tools` from scripts. I'm using that in electron/electron#26253 to get the Python linting back to working.
So merging electron/electron#26253 would cause breakage when linting for `build-tools` folks unless they have the latest `@electron/build-tools`. Could have tried to do an auto-update but that seemed headache worthy, and the need for updating `@electron/build-tools` should hopefully be uncommon enough that we can just tap people to do it. Explicitly specifying a minimum version so the feature can only be used when necessary, rather than firing on …

feat: check for @electron/build-tools updates

---

src/e-pr.js

Fixes PRs to main after https://github.com/electron/electron/pull/36106

fix: e pr for PRs to main

---

src/e-pr.js

fix: ensure e pr works

---

src/utils/xcode.js

Pending upload of new Xcode SDK.

chore: support macOS Ventura

---

src/utils/goma.js

build: add goma linux arm64 hash

---

src/utils/goma.js

- Update for changes needed for https://github.com/electron/electron/pull/36394

chore: update goma client

---

src/e-cherry-pick.js

This makes it easy to backport node commits.
E.g.
```bash
e cherry-pick https://github.com/nodejs/node/commit/09ae62b9a869ff19d634b0fd1f5a17f198cd1ae7 20-x-y
```

feat: add support for nodejs/node in the cherry-pick script

---

src/e-init.js

feat: add ability to set `target_cpu` in gn extra args

---

src/ci/ci-cancel.js
src/ci/ci-rerun.js
src/ci/ci-status.js

After this PR:
```
electron on git:roller/chromium/main ❯ e ci status -s                     1:02PM
Ref: roller/chromium/main
Circle CI
⦿ macOS - success - cee1d546-3aaf-4a69-8601-3e89e6a77806
⦿ all jobs succeeded
⦿ Linux - success - c85f8742-505c-4d01-880d-03344b510d1f
⦿ all jobs succeeded
⦿ Lint - success - f12e8ce8-78f4-4c91-8ea7-9658ff2fa822
⦿ all jobs succeeded
Appveyor
⦿ Windows x64 - running - 46084066
⦿ failed - Build - s59dbg5c08846hdb
⦿ cancelled - Test - 3363em0elrdu8439
⦿ Windows x64 (PR) - Missing
⦿ Windows ia32 - running - 46084053
⦿ failed - Build - s7bgm6989bi91mw1
⦿ cancelled - Test - boi9ytjljcyvxkuc
⦿ Windows ia32 (PR) - Missing
⦿ Windows Arm - running - 46084060
⦿ failed - Build Arm on X64 Windows - 7x0admdt7pjahlec
⦿ cancelled - Test On Windows On …
```

feat: enable jobs for Appveyor

---

src/utils/goma.js

This PR updates the GOMA SHAs to pull in needed upstream patches.

build: update GOMA SHAs

---

src/utils/xcode.js

build: update Xcode for 14.3.0

---

src/utils/xcode.js

Follow-up to https://github.com/electron/build-tools/commit/aa195fad7e6bc206655f1f85bf814c53792a646c

fix: fallback on macOS Ventura

---

src/utils/xcode.js

Refs https://github.com/electron/electron/pull/38033

fix: xcode version number extraction

---

src/e-load-xcode.js

After a macOS update folks start seeing warnings like this #444 if their machine isn't configured correctly when build-tools tries to use it's own version of xcode.
The fix for this is to ensure that your terminal application is on the list of "Developer Tools" like screenshot below.
The issue is, because we set this to be the version of Xcode everyone uses, every app that might spawn something that phones out to xcode hits this error (for instance the git plugin for vscode, fiddle, etc.).  With #417 we no longer technically needed to use `xcode-select` we just opted to leave it in for Safety™️ as it wasn't doing much harm, well, now it's doing harm 🤣.  Folks will still need to add their terminal to the list of Developer Tools but at least they also won't have to add their editor and …

fix: do not use xcode-select to override global xcode

---

.markdownlint.json
.markdownlintignore
README.md
package.json
yarn.lock

Enforcing consistency is nice.

build: lint Markdown

---

src/e-pr.js

Fixes Windows path escaping and quoting issues.

fix: e pr on Windows

---

src/utils/xcode.js

Refs https://chromium-review.googlesource.com/c/chromium/src/+/4875713

chore: add Xcode 15.0.0

---

src/utils/github-auth.js

The `gh` cli can tell us the scopes for the token, so let's make sure they're what is needed before trying to use the token.
Also tightens up error handling around the usage of `gh` cli.

chore: check token scopes before using gh cli token

---

src/e-cherry-pick.js

Adds support for dawn Gerrit links, eg.:
https://dawn-review.googlesource.com/c/dawn/+/155840

feat: support dawn cherry-picks

---

src/e-pr.js

Fixes an issue where `e pr` did not work properly for `main` in the small window between.a stable release and the release of the new nightly.
To handle this, we check if the nearest reachable tag from this commit is also the latest tag across all branches, and neither is a nightly. If that's true, we're in that small time window between a stable release and the next nightly, and should also target `main`.

fix: e pr after stable

---

src/download.js

fix: add download retry to allow for network issues

---

src/e

Refs https://github.com/electron/build-tools/pull/522.
Removes duplicated code left behind.

chore: delete extra depot_tools code

---

.github/workflows/test.yml

Run CI daily for upkeep purposes. Also lets CI be manually run.

ci: scheduled daily upkeep run

---

.github/workflows/validate-configs.yml

Validate configs to better catch typos and other mistakes which might go unnoticed.

ci: validate configs in PRs

---

src/utils/reclient.js

Will allow us to change what the default no-command thing does

chore: be explicit about the args to the cred helper

---

src/e-cherry-pick.js
src/utils/crbug.js

Updates `crbug.js` to compensate for migration to the new Chromium issue tracker.
To determine what endpoint to hit, i dug through the [included buganizer script](https://www.gstatic.com/_/buganizer/_/js/k=buganizer.b.en_US.e8zBqVLSP44.2018.O/am=wA/d=1/rs=AI3Ihhp2ogytZehIP7x8HOr1dtgZcvyAng/m=c) and found the issue fetch endpoint.
From there, i looked at the UI to find the CVE label id: 
and reverse engineered the rest to be able to pull out the CVE again.

refactor: update cherry-pick for new crbug ui

---

src/e-init.js

As in title. This doesn't fully solve the issue though so i'm also going to add another PR to allow changing an existing config more simply

feat: allow building for mas

---

src/e-cherry-pick.js

`Fixed: X` is also valid syntax for marking bug numbers

fix: support 'Fixed' syntax in crrev commits

---

src/e-build.js

feat: allow only running `gn gen` in build

---

src/utils/reclient.js

chore: update reclient helper to v0.4.0

---

src/utils/reclient.js

Needed to fix issue with fork PRs running on GHA

chore: update reclient credential helper to 0.4.1

---

src/ci/ci-cancel.js
src/ci/ci-rerun.js
src/ci/ci-status.js
src/ci/common.js

chore: remove CircleCI logic

---

src/utils/reclient.js

- Fixes https://github.com/electron/build-tools/issues/627

chore: update reclient helper to v0.4.2

---

src/e-build.js
src/utils/reclient.js

Fix an issue with reclient env values being ready when required.

fix: reclient env remote parsing

---

example-configs/evm.base.yml
src/evm-config.js
tests/evm-config.spec.mjs

Follow-up to https://github.com/electron/build-tools/pull/623
Also adds some tests.

refactor: remove lodash

---

src/utils/sdk.js

Refs https://chromium-review.googlesource.com/c/chromium/src/+/5873345.
cc @clavin

chore: add new macOS 15.0 SDK

---

src/e-cherry-pick.js

Closes https://github.com/electron/build-tools/issues/642
Rewrites `e cherry-pick` to account for Electron's commit signing requirement. It's not currently possible to sign commits via API unless you're a GitHub App, so we unfortunately need to now temporarily clone e/e and delete it later.
See https://github.com/electron/electron/pull/43799 for successful example!

refactor: rewrite cherry-pick command to account for signing requirement

---

src/utils/reclient.js

- Followup to #657; more permanent fix for using read only cache for fork PRs.

chore: update rbe helper to latest version

---

package.json
yarn.lock

build: remove unused cross-zip

---

src/download.js

chore: use streams/promises instead of promisify

---

src/utils/depot-tools.js

Needed for the chromium roll here: https://github.com/electron/electron/pull/44301

chore: update windows toolchain

---

.husky/pre-commit
package.json
src/ci/ci-cancel.js
src/ci/ci-status.js
src/download.js
src/e
src/e-auto-update.js
src/e-backport.js
src/e-build.js
src/e-cherry-pick.js
src/e-debug.js
src/e-init.js
src/e-open.js
src/e-patches.js
src/e-pr.js
src/e-show.js
src/e-sync.js
src/evm-config.js
src/utils/crbug.js
src/utils/github-auth.js
src/utils/logging.js
src/utils/paths.js
src/utils/sdk.js
tests/sandbox.js
yarn.lock

Some of these were falling pretty out of date.

chore: update dev deps

---

package.json
src/ci/ci-cancel.js
src/ci/ci-rerun.js
src/ci/ci-status.js
src/download.js
src/e-open.js
src/e-pr.js
yarn.lock

This is pretty straightforward, only `src/download.js` required more involved changes.

refactor: replace got usage with builtin fetch

---

src/evm-config.js

Remove sanitization code that's not been relevant for at least 5 major versions.

chore: remove old sanitization code

---

src/utils/depot-tools.js
src/utils/reclient.js
src/utils/sdk.js

Trying out the new cloudflare backed CDN, hopefully more stable than the old azure one that was causing us issues. cc @jkleinsc

build: try dev-cdn-experimental for dev assets (including windows toolchain)

---

vitest.config.js

A Windows test is consistently timing out on CI so bump this.

test: bump timeout

---

src/utils/sdk.js

Refs https://chromium-review.googlesource.com/c/chromium/src/+/6312080
Refs https://github.com/electron/electron/pull/45906
As in title.

chore: add macOS 15.2 SDK

---

src/e
src/utils/sdk.js

feat: allow loading a specific SDK version

---

src/utils/sdk.js

Refs https://chromium-review.googlesource.com/c/chromium/src/+/6431799

chore: add new macOS 15.4 SDK

---

src/utils/reclient.js

chore: update cred helper to v0.5.0

---

src/electron.star
src/utils/siso.js

Yeah, so it works, we move on with life...

feat: starlark overrides for siso x-compile

---

src/utils/reclient.js

Needed to pull in small fix for siso.

chore: update rbe credential helper to 0.5.1

---

src/utils/prereqs.js

Refs https://github.com/electron/build-tools/issues/739

fix: add missing fatal import

---

src/e

As in title.
<details><summary>Before</summary>
<p>
</p>
</details> 
<details><summary>After</summary>
<p>
</p>
</details>

chore: improve missing executable error
